### ISSUE TITLE
Small breaking change in 2.0.0

### ISSUE THREAD

**Issue by benjamingr** [sinonjs/lolex#108]
Hey,

Thanks for the quick release, we have 4 failing tests when updating to 2.0.0 because of old code that relied on `lolex.install(Date.now())` or something similar. (I fixed the code on our side)

I think that lolex should either `throw` a TypeError when a date is passed directly or it should accept that as the timestamp. 

I don't mind working on either suggestion - what do you think?

**Comment by fatso83** [comment]
I would rather throw an explicit `TypeError` than supporting the old (fragile) system. If you could send a patch that tries to detect uses of the old method signatures (`number`, `Date`, `arguments.length > 1`, etc) that would be most welcome.

**Comment by benjamingr** [comment]
Sure.

**Comment by benjamingr** [comment]
@fatso83 I think that the readme needs to be updated too - would you like me to do that too? (In the same PR?)

**Comment by fatso83** [comment]
haha, just made #109 , so yes please!
