### ISSUE TITLE
`nextTick`

### ISSUE THREAD

**Issue by benjamingr** [sinonjs/lolex#116]
I believe that an installation should also run `process.nextTick` calls if possible to simulate correct timer flow. 

Currently, lolex ignores `process.nextTick` calls which go out of order when testing Node calls :)

Fixing would look like:

 - detect if nextTick is present.
  - If it is, override it like `setTimeout` 
 - Whenever timers are run - always before the next timer - call the nextTick callbacks in order registered.

**Comment by benjamingr** [comment]
Submitting a PR for this

**Comment by fatso83** [comment]
Closed by #120. 

P.S. You might want to [check out this](https://help.github.com/articles/closing-issues-using-keywords/)
