### ISSUE TITLE
Domains/async hooks

### ISSUE THREAD

**Issue by benjamingr** [sinonjs/lolex#118]
Hey, 

Domains/async hooks aren't really supported from what I can tell - if a timeout is registered from a given domain/async context lolex probably wants to run it in that context.

**Comment by fatso83** [comment]
Not sure I understand what this domain bit is about (code executing in another frame?). Could you elaborate your issue description with some links to articles on the subject, and/or a short code snippet that shows what is currently not possible.

**Comment by benjamingr** [comment]
> Not sure I understand what this domain bit is about (code executing in another frame?). Could you elaborate your issue description with some links to articles on the subject, and/or a short code snippet that shows what is currently not possible.

Sure: NodeJS has the concept of [domains](https://nodejs.org/api/domain.html) (a little similar to the Zones proposal in the TC now) which are deprecated and async_hooks which are not.

Domains provide a context across asynchronous calls - and catch errors thrown in asynchronous contexts. Basically if you are in a domain and an async function is scheduled - you run it in the same domain (basically calling `domain.enter` before we `.apply` and then `domain.exit()` and wrap it in a try/catch and forward the error to the domain.

Some examples: Here is what we do at Q to support domains https://github.com/kriskowal/q/blob/master/q.js#L111-L169 and here are our tests at bluebird: https://github.com/petkaantonov/bluebird/blob/3746b7eca90dd8b11af73db5d30cf46d7dd90f9b/test/mocha/domain.js to get a better understanding.

---------

Basically:

```
// not a real implementation, just for the concept
class Domain() {
  onError() {}
  enter() { this._old = global._domain; global._domain = this; }
  exit() { if(global._domain === "this") global._domain = this._old; }
}

// now in every single asynchronous function in Node - when a callback is registered keep
// the domain as a reference and execute it, for example here is what node timers do:
// https://github.com/nodejs/node/blob/master/lib/timers.js#L250-L268
const _setTimeout = setTimeout;
setTimeout = function(callback, ms, ...args) {
   addTimer({
     callback, 
     ms, 
     args,
     domain // keep the domain around
   });
}

//And then when executing
for(const {args, domain, callback} of timersWhoseTimeCame) {
  if(domain) { // we are in a domain
    domain.enter(); // set the global domain
  }
  try {
    callback.call(null, ...args); // if this throws, its parent would handle the domain error 
  } finally {
    if(domain) domain.exit();
  }
}
```

Basically, since it's deprecated I don't feel strongly about supporting it - it was deprecated back in 2013 too and promises make the need for something like this (context across requests) a little redundant with async/await where you can just keep a local variable. That said - it's still seeing a lot of use.

Async errors are mostly for instrumenting code - and aren't really relevant here since lolex is used for testing which is typically mutually exclusive to benchmarking timer-specific code (I hope!)
