### ISSUE TITLE
`performance` should work in Node

### ISSUE THREAD

**Issue by benjamingr** [sinonjs/lolex#128]
Soon, when https://github.com/nodejs/node/pull/14680 lands the `performance` API (and tests) should be added to Node.js by lolex when running.

I'll work on it when it lands.

**Comment by mroderick** [comment]
@benjamingr are you still planning to work on this, otherwise I would like to close this issue to keep the open issues list short

**Comment by benjamingr** [comment]
Yes, this is blocked on Node atm, if you’d like you can close this and I’ll reopen it when it lands but I personally like tracking issues

**Comment by mroderick** [comment]
Cool, closing it for now
