### ISSUE TITLE
use sinon.useFakeTimers in each test on fail make other tests fail

### ISSUE THREAD

**Issue by Cherviakov** [sinonjs/lolex#131]
My function give resutl in respect to current date, I use sinon.useFakeTimesrs for that. I was trying few ways untill start to write it inside test itsel, and call restore() in the end of test.
```javascript
  describe('myFunc', function () {
    it('test case', function () {
      const clock = sinon.useFakeTimers(new Date('2017-09-23T00:00:00.00Z'));
      ...
      clock.restore();
    });
  });
```
But this approach has problems: if any test, which useFakeTimers, fails, then that other test restore function not called, making many tests fail as well, because of wrong date. 

Other approach was to put useFakeTimers in beforeEach and afterEach hooks, and then redefine this.clock in each test. That fails, because for some magic reason this.clock in afterEach appear to be undefined!
```javascript
  describe('myFunc', function () {
    beforeEach(function () {
      this.clock = sinon.useFakeTimers();
    });
    it('test case', function () {
      this.clock = sinon.useFakeTimers(new Date('2017-09-23T00:00:00.00Z'));
      ...
    });
    afterEach(function () {
     this.clock.restore(); // cannot read property restore of undefined
    });
  });
```

How to do this right, so all tests with fakeTimers were idependent?

**Comment by Cherviakov** [comment]
For now using following way:
```javascript
describe('myFunc', function () {
  it('test case', function () {
    const clock = sinon.useFakeTimers(new Date('2017-09-23T00:00:00.00Z'));
    ...
    try {
      expect(result).to.be.true;
    } finally {
      clock.restore();
    } 
  });
});
```

**Comment by fatso83** [comment]
Don't use this. Simply put the clock in a variable in the describe block's scope.

**Comment by elad-nach** [comment]
@Cherviakov the reason that `this.clock` is undefined in the `beforeEach` block is because you're instantiating a new `this` scope with the `beforeEach(function () {});` declaration.
Instead, use a an [arrow function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this#Arrow_functions) to keep `this` scope to be the enclosing block's scope.

**Comment by fatso83** [comment]
That's how to fix it, but Mocha's authors explicitly tell people to avoid arrow functions,  hence the tip to make use of closures :-)

**Comment by Cherviakov** [comment]
As I checked it, if you make arrows all but first describe, everything working fine. So I think can use that, actually.

Yeah, if put as variable in higher scope, not relate to this should be work as well okay. Thanks.
