### ISSUE TITLE
Unexpected behavior with negative delays

### ISSUE THREAD

**Issue by novemberborn** [sinonjs/lolex#134]
```js
const clock = require('lolex').createClock(0)
clock.setTimeout(() => console.log('tick'), -10)
clock.runAll()
console.log(clock.now)
```

This gives:

```
tick
-10
```

I think https://github.com/sinonjs/lolex/blob/4e1fdcf24f0adfca3b121dd51ff7505bb705a61b/src/lolex-src.js#L208 should use `Math.max(0, parseInt(timer.delay))`.

Currently these negatively delayed timers aren't triggered by `clock.tick()` either, though `clock.next()` works.

**Comment by mroderick** [comment]
Thanks for the report!

I agree with your proposed solution. Care to make a PR for it?
