### ISSUE TITLE
requestAnimationFrame and cancelAnimationFrame leaking into global scope

### ISSUE THREAD

**Issue by medanat** [sinonjs/lolex#142]
Getting "Error: global leaks detected: requestAnimationFrame, cancelAnimationFrame" when running latest version of lolex with the "--check-leaks" flag in mocha.

**Comment by mAAdhaTTah** [comment]
Whoops....

**Comment by gyandeeps** [comment]
This actually broke our unit test inside phatomjs also and they are still breaking. If if comment out any instance of `global.requestAnimationFrame` and `global.cancelAnimationFrame` then its starts working using sinon sandbox.

I am using karma, jasmine, sinon and phantomjs.

**Comment by mAAdhaTTah** [comment]
Fails with what errors?

**Comment by fatso83** [comment]
@gyandeeps, Are you sure you have the latest version of lolex, 2.3.0? This should have been fixed in #143.

**Comment by gyandeeps** [comment]
yes, i did force 2.3.0. Making the following change makes everything to function fine.

```js
var NOOP = function () { return undefined; };
var timeoutResult = setTimeout(NOOP, 0);
var addTimerReturnsObject = typeof timeoutResult === "object";
var hrtimePresent = (global.process && typeof global.process.hrtime === "function");
var nextTickPresent = (global.process && typeof global.process.nextTick === "function");
var performancePresent = (global.performance && typeof global.performance.now === "function");
// var requestAnimationFramePresent = (global.requestAnimationFrame && typeof global.requestAnimationFrame === "function");
var cancelAnimationFramePresent = (global.cancelAnimationFrame && typeof global.cancelAnimationFrame === "function");

clearTimeout(timeoutResult);

var NativeDate = Date;
var uniqueTimerId = 1;
```

**Comment by benjamingr** [comment]
@gyandeeps no need to do it - if you _don't_ want lolex to override `requestAnimationFrame` on installation `install` takes the names of the functions you want to override as a parameter.

**Comment by gyandeeps** [comment]
The code i have commented out get executed regardless during require time. This issue is only inside phantomjs. To be honest i am not using lolex directly rather sinon consumes it.

**Comment by mAAdhaTTah** [comment]
Best bet is to use `lolex` directly and tell it not to overwrite the `rAF` functions using @benjamingr's suggestion.

**Comment by gyandeeps** [comment]
To be honest, any access to code `global.requestAnimationFrame` causes the issue. Also executing the above commented lines is not optional as they get executed during `require`/`import`/parse time.

**Comment by benjamingr** [comment]
@gyandeeps interesting, I'll try to get phantomjs set up and reproduce this. Reopening in the meantime - if you can create a repo demo demonstrating the issue that'd be helpful.

**Comment by mAAdhaTTah** [comment]
Did you try it w/ the `toFake` so the `rAF` functions aren't overridden? I'm skeptical that's the issue unless there's a bug in PhantomJS.

**Comment by gyandeeps** [comment]
I will try. Its so hard and it could be many factors. I wish my code was open source then it would have been so easy. Thanks all for help. :smile:
