### ISSUE TITLE
Expose way to run just microtasks

### ISSUE THREAD

**Issue by benjamingr** [sinonjs/lolex#147]
For `jest` integration - we should consider exposing a way to run only microtasks (nextTick) - this effectively means exporting `runJobs`.

There are no other things currently shimmed in lolex with microtask semantics (promises - no because of async functions, `MutationObserver`s no). Since everything defers based on nextTick semantics that should be fine for jest inside jsdom. 

CC @SimenB

**Comment by SimenB** [comment]
We also have the inverse in Jest - just running macrotasks.

Another diff in this regard is that our `tick` just triggers timers, it doesn't touch microtasks. Again, I'm not sure in what instances the distinction is useful, but I suppose it exists for a reason 🙂 

See Jests docs (from the linked paragraph and down) for a rundown of what we do today. http://facebook.github.io/jest/docs/en/jest-object.html#jestrunallticks
Any obvious issues popping up?

**Comment by benjamingr** [comment]
I don't understand why running just macroticks and not microticks makes sense. (Since it would never be regular execution flow). Any motivation on why this is required?

**Comment by SimenB** [comment]
@cpojer (who's on vacation, so might be a bit before we get an answer) any particular use cases for this?

**Comment by cpojer** [comment]
I think running both in one call works fine with me, but I cannot confirm without testing this on the FB codebase. I can check usage of advanceTimersByTime at FB in early January to confirm.

**Comment by benjamingr** [comment]
Taking a look

**Comment by fatso83** [comment]
@benjamingr I haven't noticed the PR at all: do you have all required privileges to merge now, btw?

**Comment by fatso83** [comment]
@benjamingr You had been added to the `lolex-core` team ages ago, but I had forgotten to give `lolex-core` rights to do anything on the `lolex` repo. You should be good to write and approve stuff now! Sorry for delaying this, but a new family situation  :baby_bottle:  arose around the time of this PR.

Don't be a stranger to pestering my on email, btw, if I should be blocking something.

**Comment by benjamingr** [comment]
@fatso83 congratulations! Really no rush here or sense of urgency - family first and thanks :)

**Comment by SimenB** [comment]
@benjamingr I think I've found an issue with the implementation - it doesn't guard against recursion in the same way the timers do. Jest has the following test, which never completes when using this new function:

```js
it('throws before allowing infinite recursion', () => {
  const global = {
    Date,
    clearTimeout,
    process: {
      nextTick: () => {},
    },
    setTimeout,
  };

  const timers = new FakeTimers({
    global,
    maxLoops: 100,
    moduleMocker,
    timerConfig,
  });

  timers.useFakeTimers();

  global.process.nextTick(function infinitelyRecursingCallback() {
    global.process.nextTick(infinitelyRecursingCallback);
  });

  expect(() => {
    timers.runAllTicks();
  }).toThrow(
    new Error(
      "Ran 100 ticks, and there are still more! Assuming we've hit an " +
        'infinite recursion and bailing out...',
    ),
  );
})
```

I think `runMicrotasks` should also respect the `maxLoops` argument.

**Comment by benjamingr** [comment]
Going to reopen since it's being discussed

**Comment by SimenB** [comment]
Interesting, didn't know that! A bail seems more useful than a freeze, especially in a testing situation (as it prevents tests from timing out), but matching real behavior (beyond manipulating time) is really compelling as well.

@cpojer thoughts on this?

**Comment by cpojer** [comment]
Regardless of what's better, we cannot change behavior for existing Jest tests at this time. If we want to use lolex for Jest, the initial version must 100% match what Jest has right now. We can make incremental breaking changes later.

**Comment by benjamingr** [comment]
I'll make a PR @SimenB @cpojer

**Comment by benjamingr** [comment]
@SimenB let me know if the fix in https://github.com/sinonjs/lolex/pull/172 works for jest
