### ISSUE TITLE
Warp speed?

### ISSUE THREAD

**Issue by vroy** [sinonjs/lolex#16]
I've recently had to speed up timeouts to speed up some tests. I wrote something along the lines of this:

```javascript
oldInterval = window.setInterval
clock = lolex.install(window)
oldInterval(function() {
  clock.tick(1000)
}, 100)
```

Having something like this in lolex could be a nice addition: `clock.engageWarpSpeed(multiple)`

```javascript
clock.engageWarpSpeed(10) // 10 times faster
clock.engageWarpSpeed(2) // 2 times faster
```

Is this something that you consider merging if I open a pull request?

**Comment by cjohansen** [comment]
Hmm, what's the use case for this? If you can speed it up, why not just fake it entirely and trigger the timers yourself?

**Comment by vroy** [comment]
The app has some setTimeouts that I can't control. The idea is that the tests inject this into the app and speed up all setTimeouts equally.

**Comment by vroy** [comment]
It might very well be a niche use case and I understand if you don't want to introduce this to lolex. That's why I asked via an issue before opening a pull request.

**Comment by cjohansen** [comment]
Sure, that's great. Sorry about the late response. It just seems to me that if you can get in there and speed the timer up, you might as well just use fake ones and tick the clock ahead manually?

**Comment by vroy** [comment]
I'll close this for now.
