### ISSUE TITLE
Is method reset() public?

### ISSUE THREAD

**Issue by Alexsey** [sinonjs/lolex#161]
There is a [reset](https://github.com/sinonjs/lolex/blob/master/src/lolex-src.js#L692) method in the code but it is not in the docs (readme)

1. May I rely on it?
2. May I add to it `clock.now = 0`?

I can make a PR with it to docs

**Comment by benjamingr** [comment]
@Alexsey what's the use case?

**Comment by Alexsey** [comment]
I'm creating a single instance of `clock` per test file and then `reset` it and set `clock.now` to `0` in `mocha`'s `afterEach`

**Comment by benjamingr** [comment]
@Alexsey anything preventing you from creating a clock instance per test?

Typically our code looks like this:

```js
let clock;
befofeEach(function beforeEach() {
  clock = lolex.install();
});
afterEach(function afterEach() {
  if (clock) {
    clock.uninstall();
  }
});
```

**Comment by Alexsey** [comment]
It's much faster. Reset time and tasks is instant

**Comment by SimenB** [comment]
Jest has `reset` now. I currently implement it by doing `uninstall` then `install`, but wouldn't mind having reset out of the box :)

**Comment by benjamingr** [comment]
It also needs to reset the microtick jobs
