### ISSUE TITLE
Count of active timers

### ISSUE THREAD

**Issue by radarfox** [sinonjs/lolex#163]
Hello,

I would like to find out how many timers is actively running, but I can't find any mention of it in the API reference.

My use case is that I'm writing a test for a destructor function and I would like to make sure that all timers got cancelled after the function execution so there would be no memory leaks.

Currently I'm using this hotfix `Object.keys(clock.timers || {}).length`, but it seems quite verbose and dependent on the inner implementation.

**Comment by benjamingr** [comment]
`.uninstall` returns all the pending timers as an array. You can check its `.length` which is less hacky although I'm not sure we have this behavior documented.

Docs PR for the use case is welcome

**Comment by benjamingr** [comment]
Going to close this since I haven't received feedback in 7 days. Feel free to comment at any point.
