### ISSUE TITLE
Builds are failing on IE10 and others

### ISSUE THREAD

**Issue by fatso83** [sinonjs/lolex#167]
After merging #160 the builds [started failing](https://travis-ci.org/sinonjs/lolex/jobs/367234969#L2533). We probably lack some checks to see if the `Performance` object exists at all.

**Comment by SimenB** [comment]
Huh, we're actually hit by this in Jest in the PR moving to Lolex.

![image](https://user-images.githubusercontent.com/1404810/39768732-7659250c-52ea-11e8-8b01-1d3f2bdab1b8.png)

Probably just some faulty mocking. I can dig into it later this week if no one else gets to it 🙂

**Comment by SimenB** [comment]
Dug into this (related to #162).

Using the fix in that PR is fine, but I'm unable to install it in JSDOM as it throws with `Cannot set property performance of #<Window> which has only a getter`. This does not match Chrome behavior, which allows you to set `window.performance = {}` just fine.

Not sure of the best way forward?

**Comment by fatso83** [comment]
heads up: the fix in #162 is merged
