### ISSUE TITLE
reset should set "now" to the same value clock was installed

### ISSUE THREAD

**Issue by Alexsey** [sinonjs/lolex#183]
* Lolex version : 2.6.0
* Environment   : NodeJS

**What did you expect to happen?**
```js
const lolex = require('lolex');
const clock = lolex.install({now: 10000})
clock.reset();
console.log(clock.now) // 10000
```

**What actually happens**
```js
const lolex = require('lolex');
const clock = lolex.install({now: 10000})
clock.reset();
console.log(clock.now) // 0
```

The current behavior of `reset` is killing the sense of "now" parameter because it's getting lost after the first `reset` call

**Comment by benjamingr** [comment]
On it

**Comment by benjamingr** [comment]
Thanks for the report! Can you please verify the fix in https://github.com/sinonjs/lolex/pull/184 works for you?

**Comment by Alexsey** [comment]
For now, I have only one test case but this fix fork for it. Nice!

**Comment by benjamingr** [comment]
#184 is merged so I'm going to go ahead and close this. Feel free to reopen if you think there is still pending work to be done here.
