### ISSUE TITLE
Next release of lolex ETA?

### ISSUE THREAD

**Issue by EJLearner** [sinonjs/lolex#188]
I have seen that #181 merged to master that resolves how tests can error out if Performance is not found.

Until the next release is published, this commit isn't available through NPM, right?

I was just curious when a release with this commit is planned. We're still forcing the version to an older version so that our builds don't fail.

Thanks.

**Comment by fatso83** [comment]
It's out as 2.7.0 :+1:

**Comment by benjamingr** [comment]
> I was just curious when a release with this commit is planned. We're still forcing the version to an older version so that our builds don't fail.

Hey, this is my bad! 

I didn't realise it was a show-stopper for users and I didn't want to do another release so quickly.

Apologies - I will do better and ask next time!
