### ISSUE TITLE
Safari 9 compatibility is broken

### ISSUE THREAD

**Issue by fatso83** [sinonjs/lolex#190]
* Lolex version : 2.7
* Environment   : Safari 9

#169 assigns props in a way that's not compatible with Safari 9. That broke tests in Sinon (sinonjs/sinon#1814), which shows that we missed a browser in our browser suite (added yesterday). We should aim to support the same browsers as Sinon, given that it's the main target to support.

**What did you expect to happen?**
I expected the `test-cloud` script to pass

**What actually happens**
It fails

**How to reproduce**
Set the Sauce Labs credentials (known to Sinon maintainers) as environment variables.
`npm run test-cloud`

**Comment by benjamingr** [comment]
Is this still an ongoing issue? Do we need to PR this?

**Comment by fatso83** [comment]
[The build is still failing](https://travis-ci.org/sinonjs/lolex), so yes.
