### ISSUE TITLE
ref(), & unref() return value

### ISSUE THREAD

**Issue by icebob** [sinonjs/lolex#191]
> We understand you have a problem and are in a hurry, but please provide us with some info to make it much more likely for your issue to be understood, worked on and resolved quickly.

* Lolex version : 2.6.0
* Environment   : NodeJS v8.11

**What did you expect to happen?**
According to NodeJS documentation the `ref()` and `unref()` return the timer.
https://nodejs.org/dist/latest-v8.x/docs/api/timers.html#timers_timeout_ref

**What actually happens**
But lolex returns undefined.

**How to reproduce**
```js
const lolex = require("lolex");
const clock = lolex.install();

const timer = setTimeout(() => {}, 5000).unref();
console.log(timer);
// Prints: undefined
```
If you comment out the `lolex.install()` line, it prints the NodeJS Timeout object.

Thank you!

**Comment by fatso83** [comment]
Grep the lolex code for `unref` and see what it does (or look at the code, it's just a couple of hundred lines in one file). I haven't encountered that before. Maybe we just define the function but no implementation. Wouldn't know, but I do know we accept PRs ;)

**Comment by icebob** [comment]
yes, I checked the code, only need to change ~2 lines. I'm making a PR.
