### ISSUE TITLE
getDate returns 31

### ISSUE THREAD

**Issue by jasonkuhrt** [sinonjs/lolex#192]
This seems wrong
```
> lolex.createClock().Date().getDate()
31
> lolex.createClock().Date().toISOString()
'1970-01-01T00:00:00.000Z'
```

Why `31`? Why not `1`?

**Comment by benjamingr** [comment]
I get 1 back when I run:

```js
var lolex = require("lolex")
lolex.createClock().Date().getDate()
```

See in runkit https://npm.runkit.com/lolex

**Comment by mantoni** [comment]
That sounds suspiciously like the windows internal timer event frequency. I ran some tests once that showed that IE would fire timers at 60Hz max. However, that doesn’t make much sense here 🤔

**Comment by benjamingr** [comment]
I have been unable to reproduce - please let me know if you'd like to investigate further together and we'll figure it out.

**Comment by jasonkuhrt** [comment]
Some more info, I recently came back into contact with this topic in my work.

On my local machine I was getting the `1969` etc. date but then the _exact same code_ running in CircleCI produced different numbers.

```
    - Snapshot
    + Received

      Object {
        "fields": Array [
          Object {
            "short": false,
            "title": "Episodes",
    -       "value": "*1/10/1970*
    +       "value": "*1/11/1970*
      <https://zorro.dialogue.co/conversations/foobar4|  foobar4>
    - *1/5/1970*
    + *1/6/1970*
      <https://zorro.dialogue.co/conversations/foobar2|  foobar2>
      <https://zorro.dialogue.co/conversations/foobar3|  foobar3>
    - *12/31/1969*
    + *1/1/1970*
      <https://zorro.dialogue.co/conversations/foobar1|  foobar1>",
          },
        ],
      }

      50 |     ],
      51 |   }
    > 52 |   expect(createForCaseOfData(data)).resolves.toMatchSnapshot()
         |                                              ^
      53 | })
      54 | 

      at Object.toMatchSnapshot (node_modules/expect/build/index.js:175:22)
      at Object.<anonymous>.it (plugins/hollywood.spec.ts:52:46)
```

CircleCI is using `  image cache not found on this host, downloading circleci/node:8.11`

My local Node was:

```
❯ node -v
v8.11.1
```

**Comment by jasonkuhrt** [comment]
I believe my issue is this: https://stackoverflow.com/questions/38341414/date-getdate-wrong-value-from-iso-8601-date-instance. I am in Montreal.
