### ISSUE TITLE
Error in browser: Uncaught ReferenceError: global is not defined

### ISSUE THREAD

**Issue by budarin** [sinonjs/lolex#198]
* Lolex version : 2.7.1
* Environment   : Chrome 68.0.3440.106, Windows
* Other libraries you are using: no

**What did you expect to happen?**
expet to have window.lolex to be accesible

**What actually happens**
error at:
`var defaultImplementation = withGlobal(global || window);`

**How to reproduce**
to include tag into page's head
`<script src="https://cdn.jsdelivr.net/npm/lolex@2.7.1/src/lolex-src.min.js" crossorigin></script>`
even if to patch this
`global = window`

next error occures at 
`exports`

**Comment by benjamingr** [comment]
Checking.

**Comment by benjamingr** [comment]
PR at https://github.com/sinonjs/lolex/pull/199 - sorry for this! Thanks for the report.

**Comment by benjamingr** [comment]
You need https://cdn.jsdelivr.net/npm/lolex@2.7.1/lolex.min.js and not https://cdn.jsdelivr.net/npm/lolex@2.7.1/src/lolex-src.min.js

**Comment by budarin** [comment]
thanks, it solves the problem!
