### ISSUE TITLE
Remove dependency to Sinon

### ISSUE THREAD

**Issue by mantoni** [sinonjs/lolex#2]
Since this module is supposed to power Sinon in the future, we should remove the dependency, or replace it with a dependency on a pure `sinon-stub` module (once that is available).

**Comment by fatso83** [comment]
Is this really an issue? `sinon` is only a `devDependency` and is only used in the tests. I do not see the problem. With the version of `sinon` in master we could just as well replace `sinon.stub` with `sinonStub = require('sinon/lib/stub')`, although I don't see what that brings to the table. Extracting all the various bits of `sinon` into their sub-repos comes with a lot of administrative baggage, and I do not see any benefit in this case.

**Comment by mantoni** [comment]
This should be a long-term goal. It's not really necessary, but having circular dependencies sometimes come with weird issues. If you do a fresh npm install after a lolex release, it has it's own code in node_modules.

**Comment by fatso83** [comment]
@mantoni still not sure what you mean by "having its own code in node_modules". It does not, if

**Comment by fatso83** [comment]
@mantoni still not sure what you mean by "having its own code in node_modules". If you install it as a dependency it has no further dependencies that will get installed in `node_modules`. But maybe you think about a fresh install when developing the module? In which case, the answer is _kind of_, as the sinon version we use is too old to include `lolex`, but the code is still _included in the source code of sinon_ ...

**Comment by mantoni** [comment]
Yes. I thought we might end up with Lolex -> Sinon -> Lolex, but you're right, that doesn't happen if we don't depend on Sinon 2 here. To me it's a red flag to have circular dependency, but it's more a feeling, maybe there is no good reason in this case. It's not really an issue. Closing.
