### ISSUE TITLE
reset() does not reset high-resolution timer

### ISSUE THREAD

**Issue by novemberborn** [sinonjs/lolex#206]
* Lolex version : 2.7.4

**What did you expect to happen?**

`reset()` resets the high-resolution timer.

**What actually happens**

The high-resolution timer is not reset.

**How to reproduce**

```js
const clock = lolex.install()
clock.now === 0
clock.tick(20)
clock.hrNow === 20
clock.reset()
clock.now === 0
clock.hrNow === 20
```

**Comment by benjamingr** [comment]
PR welcome, otherwise I can work on this in October happily :)
