### ISSUE TITLE
High-resolution timer gets tripped up by floating point arithmetic

### ISSUE THREAD

**Issue by novemberborn** [sinonjs/lolex#207]
* Lolex version : 2.7.4

**What did you expect to happen?**

Advancing the clock with fractional milliseconds should give me an integer nanosecond value when I call `process.hrtime(prev)`.

**What actually happens**

The nanosecond value is a float, not an integer.

**How to reproduce**

```js
const clock = lolex.install()
clock.tick(1022.7791)
clock.hrtime([0, 20000000]) // [ 1, 2779099.999999881 ]
```

The reproduction advanced the clock by a fraction of a nanosecond. I suppose it'd be fine to round the computed nanosecond value, but I'm not sure if it should be rounded up or down. Alternatively something like https://www.npmjs.com/package/decimal.js may help to avoid the floating point arithmetic. Perhaps `tick()` should round down to the closest nanosecond, but I'm not sure if that'll help or not.

**Comment by benjamingr** [comment]
An alternative would be to have `clock.tick` accept a `BigInt` optionally or expose a tickPrecise that takes a `BigInt` of nanoseconds.

I can look into this when I get back from holiday at the beginning of October

**Comment by novemberborn** [comment]
`BigInt` support isn't widespread yet. I think `tick` could take fractions, but the calculations have to be done differently.

**Comment by SimenB** [comment]
@fatso83 is it acceptable to add a dependency here to handle the maths of it? floating point arithmetics sucks :(

**Comment by fatso83** [comment]
I'd say lets go with the simplest thing that seems to work and if people find edge cases we haven't thought of, we will fix it in time. `Math.round` seems fine to me and it will probably fix the 99% immediately. I am not an expert or authority in this matter, so no strong feelings.

**Comment by novemberborn** [comment]
This is still a problem. From #210:

> If someone ever gets a problem with round-off errors ... we'll tackle it then.

👋 

Starting from `742` milliseconds, ticking by `123.493` milliseconds ends up rounding to `865492920` nanoseconds.

Try in your REPL:

```console
❯ node -pe "742 + 123.493"                                                                                                           8.12.0
865.4929999999999
```

A different approach may be to do the computations in nanoseconds directly. I think that should be fine, integer wise, unless you start doing ticks larger than a 100 days worth of nanoseconds.

**Comment by SimenB** [comment]
```sh-session
$ node -p '(742 * 1e9 + 123.493 * 1e9) / 1e9'
865.493
```

maybe?

**Comment by fatso83** [comment]
@novemberborn I am not sure I see the problem wrt lolex. We round off the numbers, meaning it should round up in your case. Can you demonstrate that the problem mentioned in this issue at the top isn't solved?

Your demo only shows how floating points are representing. Since we don't truncate that value, rather rounding it, how does the problem manifest?

**Comment by novemberborn** [comment]
> We round off the numbers, meaning it should round up in your case. Can you demonstrate that the problem mentioned in this issue at the top isn't solved?

My example came from using lolex:

> Starting from `742` milliseconds, ticking by `123.493` milliseconds ends up rounding to `865492920` nanoseconds.

Note the value is `865492920` not `865493000`.

**Comment by fatso83** [comment]
That's not a verification step. I made a [runnable example using the 2.7.5 release](https://runkit.com/fatso83/5ba22fbb15a4e300122a4670) and it shows the correct result: `845493000`.

So, no, I am not convinced we have a bug :smile_cat:  Can you make sure you are running 2.7.5, not 2.7.4? I don't like to have bugs in our code, so of course, prove me wrong if I am!

**Comment by novemberborn** [comment]
Here you go: https://runkit.com/novemberborn/5ba363ba0f73fb001265cb0f

The difference should be `123493000` but I get `123492920`.

**Comment by fatso83** [comment]
Verified. The good thing is that we know have verifiable test cases 😁 

I see two paths forwards:
1. The "correct one

**Comment by novemberborn** [comment]
You'd have to separate the seconds from the nanoseconds in your internal representation though, right?

**Comment by novemberborn** [comment]
It's probably OK to keep the storage in milliseconds, and then have separate storage for the remainder down to the nanosecond.

If ticks are presented as integers, then you don't need to touch the remainder. If it's a float then you adjust the remainder, and if it ticks over (positively or negatively) adjust the milliseconds.

The nanoseconds value should be truncated to always remain an integer. E.g. if I tick by `0.0000009` milliseconds, then just treat that as a `0`, since it'd be `0.9` nanoseconds.

**Comment by fatso83** [comment]
@novemberborn So, in general, you propose we go ahead with (a modified of) the first  approach? Store integers internally (even if it means a tad more logic for two numbers).

**Comment by novemberborn** [comment]
@fatso83 yes, but you only need to use the second value if the tick amount is fractional. If we're ticking by seconds or milliseconds then it doesn't impact the nanosecond values at all.

**Comment by mroderick** [comment]
I think this would be a valuable upgrade to `lolex`.

Reading the discussion is interesting, but it's easy to overlook things. @novemberborn @fatso83 could you write up a little proposal (perhaps just in the original entry above) and specify exactly what changes need to be made, how we verify that the work is correct and complete?

**Comment by mroderick** [comment]
Awesome, now we just need someone to do the work :)

**Comment by fatso83** [comment]
Argh, I started this in a fork of mine (see above ref), but I have used three hours trying to make my initial test cases pass. I tried several variations after finding there are so many corner cases when we support negative ticks! The essence of the trouble is this: I am not totally sure what the "right" integer value for millisecond is at times. Depends on using `fixedFloor` or `Math.floor`() and what happens around 0.

---

# Cases that needs to be agreed upon
These all revolve around the integer value of `Date.now()`. `hrtime` can be ignored for the moment.

## now=0.1, tick=-1
Pre: Date.now() == 0?
Post: Date.now() == 0?

## now=1.1, tick=-1
Pre: Date.now() == 1
Post: Date.now() == 0

## now=-0.3, tick=0.4
Pre: Date.now() == 0?
Post: Date.now() == 0?

## now=-1.3, tick=0.4
Pre: Date.now() == 1?
Post: Date.now() == 0?

**Comment by mroderick** [comment]
Perhaps we should spend some time refactoring the affected parts of the code, write better tests for the existing code ... all to make it easier to work with?

**Comment by benjamingr** [comment]
I'm absolutely fine with even throwing on negative ticks, I had no idea it was supported to begin with.

**Comment by fatso83** [comment]
I managed to fix the remaining test in a simple manner, so I'll submit a PR shortly. I'll add a test for throwing on negative ticks as well.

**Comment by fatso83** [comment]
@novemberborn I think #214 should itch your scratch. Would you mind checking it out and seeing if it solves your issues?
