### ISSUE TITLE
Thanks 🙏❤️

### ISSUE THREAD

**Issue by ryanwmarsh** [sinonjs/lolex#212]
I just wanted to say 👍 thank you to the contributors. Lolex just saved me a ton of time (no pun intended), and was trivial to set up and use in my tests. 

🎉🎉 **Thank you!**  🎉🎉

**Comment by mroderick** [comment]
As best I can tell from git history, @cjohansen was the original author. He extracted `lolex` from `sinon` with dbd7d17029f5b258aa14422b74798c844de8bfab in 2014. There were probably other contributors from that era that could also be considered OG.

**Comment by fatso83** [comment]
Thank you for those nice words, @ryanwmarsh. It's stuff like that that makes people contribute :-) 

P.S. I don't know about me being primary maintainer. I always regarded Morgan as the primary maintainer :-) I guess the term is a fleeting concept, based on who has time available, and currently that isn't usually me :baby:  :baby_bottle:

**Comment by benjamingr** [comment]
Thanks @cjohansen !

**Comment by n-rook** [comment]
I just came by to say the same thing. This library is fun to use and makes my daily life easier. Thanks ❤️
