### ISSUE TITLE
Changes in v3.0.0

### ISSUE THREAD

**Issue by gr2m** [sinonjs/lolex#216]
Hello there! 

Thank you so much for lolex, I use it in a ton of my projects and it’s working great!

I wonder if you keep track of changes for the released versions somewhere? If not, could you add some for the latest v3 release: https://github.com/sinonjs/lolex/releases/tag/v3.0.0?

**Comment by gr2m** [comment]
To add some more context, the release notes are added to pull requests by Greenkeeper which makes it very simple for folks to understand and merge a dependency update PR. Plenty of PRs are already open for lolex v3 :: https://github.com/search?q=%22Update+lolex+to+the+latest+version%22+is%3Aopen&type=Issues

For comparison, here is a PR that includes the release notes right in the pull request: https://github.com/octokit/rest.js/pull/1018

![image](https://user-images.githubusercontent.com/39992/46623396-5a3a7400-cae2-11e8-84ad-c6ad4c4e76a0.png)

**Comment by SimenB** [comment]
There is https://github.com/sinonjs/lolex/blob/master/History.md

What's needed for the bots to pick them up? Naming the file changelog instead?

**Comment by gr2m** [comment]
Oh my, apologies, I somehow managed to miss that file :facepalm:

I don’t think there is a way for Greenkeeper to pick that up, but no worries, it’s only a click away, good enough :)

Thanks again for the great work

**Comment by benjamingr** [comment]
Thanks for opening the issue :)
