### ISSUE TITLE
Docs Tasks

### ISSUE THREAD

**Issue by benjamingr** [sinonjs/lolex#219]
The lolex docs could use some love.

Currently we don't have a table of contents to the API documentation and it's all in the readme.

The docs at the moment are not too great (at least the parts I added :D).

Some ideas for improvement for people to pick up (**priority for first time contributors for whom its the first issue**):

 - [ ] Add table of contents for API documentation
 - [ ] Revise overview of what lolex does and clarify it
 - [x] Split the API documentation into a different markdown page with a link from the README.
 - [ ] Clarify the types of parameters passed to different functions (like in `.install`)
 - [ ] Add links to MDN/WHATWG/Node.js API docs for different objects mocked.
 - [ ] Revise and improve issue templates.
 - [x] Add CONTRIBUTING.md and move the instructions please. (and hopefully reuse content from main sinon project)
 - [ ] Migrate documentation to https://sinonjs.org/ through the main repo as outlined in the [documentation overhaul issue](https://github.com/sinonjs/sinon/issues/1651)
   - [ ] Add documentation addition process after said migration to the process

I promise to review any such changes people make :)

**Comment by mgred** [comment]
Hey @benjamingr,

I completely agree with you, `lolex` is definitely worth a great documentation!

There is already an [issue](https://github.com/sinonjs/sinon/issues/1651) which proposes a documentation overhaul of all _SinonJS_-Projects.

> Some ideas for improvement for people to pick up

Apart from the content, a first start might be to adopt the structure and tools we use in all other projects. It's actually just MkDocs to translate a single Markdown file living in a `docs` folder.

Regarding `README` and `CONTRIBUTING.md`, we could also use the files from our other projects as an inspiration (or kind of template) to be convenient with them, I think.

I'm in helping to push this forward!

**Comment by benjamingr** [comment]
Thanks, that's very helpful @mgred! 

I think that reusing content from the CONTRIBUTING.md makes a ton of sense and ditto for the README. The work outlined here can still be done IMO (ditto issue templates).

I'll read and then edit things in based on that issue - feel free to edit my "asking for help" message as you see fit!

**Comment by mgred** [comment]
Cool, @benjamingr 

I would grab a task and start restructuring the docs:

* [ ] move it from the `README` as a first act
* [ ] and put a ToC

We could then have a first look on what a separate documentation would look like. Because we already have a good basis, it shouldn't be that hard to polish the docs.

**Comment by benjamingr** [comment]
Sounds good to me - I thought this could be a great "good first contribution" issue for new contributors to ease them into the project - if you want to take something from here by all means feel free :)

**Comment by rjseymour66** [comment]
Hi All,

I am a professional technical writer, but I am new to Github.  I am looking for a good project to contribute get my feet wet.

I see there is already some activity here and want to make sure I am not stepping on anybody's toes!

Please let me know if I can help, and I will gladly jump right in!

- Ryan

**Comment by mgred** [comment]
Hey @rjseymour66 welcome aboard :tada:

I already started on this with splitting the `README.md`. I will create a PR asap and let you know. You could then give some feedback and grab a task you want to tackle, I guess.
How about that?

**Comment by benjamingr** [comment]
@rjseymour66 that sounds lovely! Thanks a lot - sure, just grab anything you want :)

**Comment by mgred** [comment]
I have a first screenshot:

* It was generated using `MkDocs` with the same config we use in some other projects. 
* almost all from the `README.md` and made just some small structural changes. I 
* also put some links to MDN and nodejs documentation plus some internal
* split the api reference into `lolex` and `clock`
* highlight **lolex**, everywhere :smile: 
* shorter method headlines

Any thoughts?

![localhost_4000_](https://user-images.githubusercontent.com/2325260/47224545-138b2a80-d3bc-11e8-886e-46dde7e886b6.png)

**Comment by benjamingr** [comment]
@mgred awesome! Some questions

 - Can we get links to the clock methods on the side? (I think mkdocs can do this, can investigate if you don't want to engage with it)
 - Can we add a link from the README to the docs? (in the same PR)

**Comment by benjamingr** [comment]
Also Ryan (@rjseymour66) if you could review the PR @mgred made from a technical writer's PoV that would be immensely helpful!

**Comment by mgred** [comment]
@benjamingr 
> Can we get links to the clock methods on the side? (I think mkdocs can do this, can investigate if you don't want to engage with it)

What do you exactly mean with that?

> Can we add a link from the README to the docs? (in the same PR)

It is already https://github.com/sinonjs/lolex/pull/221/commits/67723ca7366b2b14d9a75ddcf4b9ce5f6d87d582#diff-1e290ac8433d555bce009b162cb869d0L15 We just need to setup github pages Ithink

**Comment by benjamingr** [comment]
> What do you exactly mean with that?

That the sidebar will show the actual methods and not just "Clock API", "lolex API" and "usage" but also things like "clock.install()` and `clock.tick`

**Comment by mgred** [comment]
Ahh okay, understand. I don't know if MkDocs can do this. Personally I think its fine to have it like this, since all other projects also just list the second level headings on the left sidebar.

**Comment by rjseymour66** [comment]
Hi All,
Sorry - been out of pocket for the last few days.

mgred - this looks great!  I can look it over in the next few days and provide some feedback.

I will also take a look at other tasks for contribution.  Looking forward to it!

**Comment by rjseymour66** [comment]
Please excuse my inexperience, but I want to make sure I am making suggestions correctly. I have a few questions:

1. This is the doc to review, correct? [WIP] Documentation prototype #226
2. How should I make my suggestions?  Just click the "+" in the source diff view and type in the Leave a Comment area?

Again, I'm sorry if these are stupid questions, but I am brand new to Github - thanks!

**Comment by mgred** [comment]
@rjseymour66 
No worries! Please keep asking if something is unclear for you.
 
> This is the doc to review, correct? [WIP] Documentation prototype #226 

#226 is different from this issue and it really seems a bit confusing. 
This issue here is intended to give a bit more love to the **lolex** docs in general and align it with the other sub projects, where #221 is the corresponding PR.

#226 is the PR to a prototype as an approach to sinonjs/sinon#1651 where #222 is the issue. This ia more and experiment we try but has nothing to do with the **lolex** docs itself. Nevertheless, if you have suggestions please, don't hesitate to leave comments :+1:  

> How should I make my suggestions? Just click the "+" in the source diff view and type in the Leave a Comment area?

Yes this is how it works :+1: Put any suggestions below a line of code and start a new discussion.
