### ISSUE TITLE
Documentation Prototype

### ISSUE THREAD

**Issue by mgred** [sinonjs/lolex#222]
@mroderick and I had a chat today on how to tackle sinonjs/sinon#1651

We would like to have a starter with one of our smaller projects to explore the possibilities on how to align and scale all our documentations across the projects.
Also, we aim to have more _easy-to-maintain_ documentation to encourage more contributions.

### Some Ideas so far

**General**
* [ ] Starting off with the Jekyll Setup of the main project
* [ ] Adopt our current theme
* [ ] Optimize for larger displays

**API docs**
* [ ] Split API docs -> one function per page
* [ ] Runnable Examples (There is some effort made already in sinonjs/sinon#1794)

We thought lolex could be a great start. We're in the middle of some refactoring (#219, #221) already and could just continue from there on.

As usual, there is nothing set in stone. Any feedback is appreciated :+1:

**Comment by benjamingr** [comment]
Sounds great to me :) Thanks for working on this and picking this up!
