### ISSUE TITLE
clearInterval(intervalId) results in infinite loop with clock.runAll()

### ISSUE THREAD

**Issue by jshado1** [sinonjs/lolex#224]
```
Error: Aborting after running 50 timers, assuming an infinite loop!
  at Object.runAll (node_modules/lolex/src/lolex-src.js:753:19)
```

* Lolex version : `3.0.0`
* Environment   : NodeJS `10.7.0`
* Other libraries you are using: Enzyme `3.7.0`, Mocha `5.2.0`, SinonChai `3.2.0`

**What did you expect to happen?**
The interval to be cancelled.

**What actually happens**
The interval continues indefinitely.

**How to reproduce**
```jsx
class Test extends React.PureComponent<{},{}> {
    // …
    doSomething = () => {
        someDep();
    }
    componentDidMount() {
        this.intervalId = setInterval(this.doSomething, 10000);
    }
    componentWillUnmount() {
         clearInterval(this.intervalId);
    }
    // …
}
```

```jsx
describe('<Test/>', () => {
    const sandbox = createSandbox();
    const ss = {};

    before(() => {
        ss.someDep = sandbox.stub(someDep, 'default');
        ss.clock = sandbox.useFakeTimers({
            loopLimit: 50,
        });
    });

    afterEach(() => {
        sandbox.resetHistory();
    });

    after(() => {
        sandbox.restore();
    });

    it('should stop after unmount', () => {
        shallow(<Test />)
            .unmount();

        ss.clock.runAll();
        expect(ss.someDep).to.have.been.calledOnce;
    });
});
```

<details>
<summary>Log of intervalId and clearInterval from within componentWillUnmount()</summary>

**`intervalId`**:

```js
{ id: 36,
  ref: [Function: ref],
  unref: [Function: unref],
  refresh: [Function: refresh] }
```

**`clearInterval`**:

```js
{ [Function]
  hadOwnProperty: true,
  clock:
   { now: 10000,
     timeouts: {},
     Date:
      { [Function: ClockDate]
        now: [Function: now],
        toString: [Function: toString],
        parse: [Function: parse],
        UTC: [Function: UTC],
        clock: [Circular],
        hadOwnProperty: true },
     loopLimit: 50,
     setTimeout: { [Function: setTimeout] hadOwnProperty: true },
     clearTimeout: { [Function: clearTimeout] hadOwnProperty: true },
     nextTick: [Function: nextTick],
     setInterval: { [Function: setInterval] hadOwnProperty: true },
     clearInterval: { [Function: clearInterval] hadOwnProperty: true },
     setImmediate: { [Function: setImmediate] hadOwnProperty: true },
     clearImmediate: { [Function: clearImmediate] hadOwnProperty: true },
     countTimers: [Function: countTimers],
     requestAnimationFrame: [Function: requestAnimationFrame],
     cancelAnimationFrame: [Function: cancelAnimationFrame],
     runMicrotasks: [Function: runMicrotasks],
     tick: [Function: tick],
     next: [Function: next],
     runAll: [Function: runAll],
     runToFrame: [Function: runToFrame],
     runToLast: [Function: runToLast],
     reset: [Function: reset],
     setSystemTime: [Function: setSystemTime],
     hrtime: { [Function: hrtime] hadOwnProperty: true },
     uninstall: [Function],
     methods:
      [ 'setTimeout',
        'clearTimeout',
        'setImmediate',
        'clearImmediate',
        'setInterval',
        'clearInterval',
        'Date',
        'hrtime' ],
     _setTimeout: { [Function] hadOwnProperty: true, clock: [Object] },
     _clearTimeout: { [Function] hadOwnProperty: true, clock: [Object] },
     _setImmediate: { [Function] hadOwnProperty: true, clock: [Object] },
     _clearImmediate: { [Function] hadOwnProperty: true, clock: [Object] },
     _setInterval: { [Function] hadOwnProperty: true, clock: [Object] },
     _clearInterval: { [Function] hadOwnProperty: true, clock: [Object] },
     _Date:
      { [Function: ClockDate]
        now: [Function: now],
        toString: [Function: toString],
        parse: [Function: parse],
        UTC: [Function: UTC],
        clock: [Object],
        hadOwnProperty: true },
     _hrtime: { [Function] hadOwnProperty: true, clock: [Object] },
     restore: [Function],
     timers:
      { '33': [Object], '34': [Object], '35': [Object], '36': [Object] },
     duringTick: false } }
```

</details>

**Comment by benjamingr** [comment]
Sorry for the (perhaps silly?) question - I am not too familiar with enzyme.

Can you verify that if you add `console.log`s in the didMount and willUnmount calls they both get called exactly once and if so - does the problem reproduce if you remove the `shallow(<Test />).unmount()` with just the contents of its hooks?

**Comment by jshado1** [comment]
@fatso83 I don't see why it _wouldn't_ have the same result without React. There's nothing special about the imports, but I can add them. I tried to upload a mini-repo to github last night, but that part of GitHub was down.

@benjaminger yes, I already verified both the didMount and willUnmount are called only once ;) I did not verify the `shallow().unmount()` because that's what causes the willUnmount to fire (it does not fire without the unmount()), and thus `clearInterval` does not get called (so the problem would not be exposed).

**Comment by benjamingr** [comment]
GitHub deleted my comment :/

**Comment by fatso83** [comment]
[GitHub is flaky today](https://status.github.com/messages)

**Comment by benjamingr** [comment]
Repro here: https://gist.github.com/benjamingr/b89b87d854a9c8f785e7b7cc4d953c9f

need to first `npm i react chai sinon enzyme react-dom enzyme-adapter-react-16 mocha` and then repro with `npx mocha index.js` (or whatever you saved the gist as)

**Comment by jshado1** [comment]
@benjamingr when I switch my actual to `.tick(1000)`, it works (it gets called exactly the number of expected times). However, switching it back to `runAll()` still causes the infinite loop. I can't get your pastebin to pass: `called` is always 0 (but I don't get the infinite loop).

Am I misunderstanding what `runAll()` does? I expect `ticket(1000)` in this situation to be effectively the same as `runAll()`.

>**`clock.runAll();`**
>This runs all pending timers until there are none remaining. If new timers are added while it is executing they will be run as well.
>
>This makes it easier to run asynchronous tests to completion without worrying about the number of timers they use, or the delays in those timers.

**Comment by benjamingr** [comment]
@jshado1  thanks for following up! I appreciate it!

`runAll` runs "forever" - all pending clocks run until there are no pending items - this means intervals run forever for example unless they are cleared (there is runToLast - are you looking for that?)

Can you update my gist above to reflect the bad example so we're sure we're talking apples-to-apples? I really want to get to the bottom of this and figure out if we have a bug :)
