### ISSUE TITLE
Error: Native setTimeout will not work when Date is faked

### ISSUE THREAD

**Issue by moll** [sinonjs/lolex#23]
Hey,

What's with that warning? Upgrading Sinon's minor version number broke my tests, which seem to be caused by Lolex. Downgrading to Sinon v1.15 (with an older ver of Lolex) removed the warning and tests continued to work. No `setTimeout` mocking necessary.

Thanks!

**Comment by cjohansen** [comment]
Do you have some more information? I am not seeing this in any of my projects. Are you calling `useFakeTimers` in your code when you don't need it?

**Comment by moll** [comment]
Hey. Aye. By "No setTimeout mocking necessary" I meant using the following has worked a-okay for a while now: `Sinon.useFakeTimers(+NOW, "Date")`.

**Comment by cjohansen** [comment]
I see. Well, the error is thrown to save you the frustration that will follow if you do that on node and try to use `setTimeout` - it will not work. Are you actually using `setTimeout`? If not, you could simply add it to the list of functions?

We *could* make this warnings instead of hard errors, but I really don't think you should be doing this, as it's likely to cause trouble. @mantoni @mroderick opinions?

**Comment by moll** [comment]
Oh, adding `setTimeout` et alii for code that depends on it for deferring tends to break it. And I don't want to bother ticking along manually just because their implementation happened to use `setTimeout`. :) I'm only explicitly interested in mocking time and that's why `useFakeTimers` takes names, doesn't it? :)

**Comment by moll** [comment]
And no warnings for me, thank you. ^-^ _Only_ a fake `Date` object, please.

**Comment by cjohansen** [comment]
I guess we could restrict the error to be thrown on Node. Would need to check if this is the case in any other environment as well.

**Comment by cjohansen** [comment]
Using a fake `Date` and relying on `setTimeout` means your code will definitely not run on Node.

**Comment by moll** [comment]
Hmm, but I _am_ using Node. What's the problem it's meant solve? Faking `Date` is a different concern from faking timers.

**Comment by cjohansen** [comment]
Weird. You'd think they are separate issues, but:

```sh
> global.Date = function () {}
[Function]
> setTimeout(function () { console.log('Hey'); }, 100);
TypeError: Object function () {} has no method 'now'
    at insert (timers.js:53:26)
    at Object.exports.active (timers.js:179:7)
    at exports.setTimeout (timers.js:225:11)
    at global.setTimeout (node.js:174:27)
    at repl:1:1
    at REPLServer.self.eval (repl.js:110:21)
    at repl.js:249:20
    at REPLServer.self.eval (repl.js:122:7)
    at Interface.<anonymous> (repl.js:239:12)
    at Interface.emit (events.js:95:17)
```

**Comment by cjohansen** [comment]
Weirdly enough, it does work if the faked `Date` has a `now` function, even if it always returns the same number. Ok, will remove the error.

**Comment by moll** [comment]
What version of Node is that? v0.12.7 doesn't throw with a replaced `Date`...

I've used the explicit `useFakeTimers` thing for some time now ever since I noticed faking `setImmediate` by default broke all kinds of promise libraries. And probably better to be explicit anyways as they _are_ different concerns and implementation-dependent tests are flaky. ;-)

> Ok, will remove the error.

Yay.

**Comment by cjohansen** [comment]
I somehow managed to not push Sinon last night, so I won't be able to fix the problem in Sinon until I get to my home computer.

**Comment by moll** [comment]
No biggie. Thanks. Clamping Sinon to `<1.16` was a quick fix.

**Comment by fatso83** [comment]
Any status here? Not sure if this was resolved anywhere?

**Comment by fatso83** [comment]
Closing as lack of information.

**Comment by moll** [comment]
I'll report if it still doesn't work once I get around to upgrading Sinon. Trying to live the "if it works, don't fix it" principle with updates. ;-)
