### ISSUE TITLE
Provide a way to tell if the clock has been mocked

### ISSUE THREAD

**Issue by TimothyJones** [sinonjs/lolex#234]
* Lolex version : latest
* Environment   : node
* Other libraries you are using: pact

It would be useful if we could detect the difference between a mocked clock and the real one.

The use case for this is where we have a testing framework that uses the clock internally (such as [Pact](http://pact.io/), an API contract testing framework that spins up mock servers).

If `sinon` is used to mock the clock during a test, pact [doesn't start properly](https://github.com/pact-foundation/pact-node/issues/110) and the tests hang (because Pact ends up using the mocked clock).

It'd be nice if Pact could detect the mocked clock and throw a warning during the test. Is providing a way to tell that the clock has been mocked something you could support? Is there another work around I am not seeing?

**Comment by benjamingr** [comment]
Hey, sorry for the lack of response. You can get a reference to the original timers before your code and then compare the reference of the global setTimeout afterwards.
