### ISSUE TITLE
Support hrtime.bigint()

### ISSUE THREAD

**Issue by novemberborn** [sinonjs/lolex#235]
> We understand you have a problem and are in a hurry, but please provide us with some info to make it much more likely for your issue to be understood, worked on and resolved quickly.

* Lolex version : 3.1.0
* Environment   : Node.js 10.15.3
* Example URL   : N/A
* Other libraries you are using:

**What did you expect to happen?**

My code uses [`process.hrtime.bigint()`](https://nodejs.org/api/process.html#process_process_hrtime_bigint). When stubbing `process.hrtime` using Lolex, this method is no longer available.

On platforms that don't provide this function, I'd expect it not be made available by Lolex either.

**What actually happens**

It returns the stubbed time, as a BigInt.

**How to reproduce**
> Describe *with code* how to reproduce the faulty behaviour
> or link to code on JSBin or similar

```console
$ node                                                                                                                                            > process.hrtime.bigint()
39069092115824n
> require('lolex').install({toFake: ['hrtime']})
{ now: 0, … }
> process.hrtime.bigint()
TypeError: process.hrtime.bigint is not a function
```

**Comment by benjamingr** [comment]
Sounds perfectly reasonable!

**Comment by novemberborn** [comment]
I'm still working on getting my tests to pass, but this seems to be a good implementation:

```js
  process.hrtime.bigint = () => {
    const [seconds, nanoseconds] = process.hrtime()
    return BigInt(seconds) * BigInt(1e9) + BigInt(nanoseconds) // eslint-disable-line no-undef
  }

```

**Comment by benjamingr** [comment]
So, it looks like [`.bigint()`](https://github.com/nodejs/node/blob/864860e9f3d4eed0b0b81af55197d7e525ea6306/src/node_process_methods.cc#L157-L161) just returns:

```
static void HrtimeBigInt(const FunctionCallbackInfo<Value>& args) {
  Local<ArrayBuffer> ab = args[0].As<BigUint64Array>()->Buffer();
  uint64_t* fields = static_cast<uint64_t*>(ab->GetContents().Data());
  fields[0] = uv_hrtime();
}
```

Whereas hrtime does:

```
static void Hrtime(const FunctionCallbackInfo<Value>& args) {
  uint64_t t = uv_hrtime();

  Local<ArrayBuffer> ab = args[0].As<Uint32Array>()->Buffer();
  uint32_t* fields = static_cast<uint32_t*>(ab->GetContents().Data());

  fields[0] = (t / NANOS_PER_SEC) >> 32;
  fields[1] = (t / NANOS_PER_SEC) & 0xffffffff;
  fields[2] = t % NANOS_PER_SEC;
}
```

So in order to support it we could just do `return new BigInt(clock.now - adjustedSystemTime[0] - start)` or something similar.

Would you like to work on a PR?

**Comment by novemberborn** [comment]
> Would you like to work on a PR?

Happy to, but if somebody else wants to pick this up before I get round to it please feel free.
