### ISSUE TITLE
An option to call "simultaneous" handlers in reverse order

### ISSUE THREAD

**Issue by rpominov** [sinonjs/lolex#24]
Currently when two handlers set to be called at the same time, lolex guarantees that they will be called in the order they were set.

For example in the following setup `foo` is always called first:

```js
setTimeout(foo, 1000);
setTimeout(bar, 1000);
```

Although this is not guaranteed by the real implementations of `setTimeout` and friends: 
 - http://stackoverflow.com/questions/1776239/are-equal-timeouts-executed-in-order-in-javascript/5998338#5998338
 - https://code.google.com/p/chromium/issues/detail?id=172587
 - https://bugs.webkit.org/show_bug.cgi?id=111143

So while tests may pass, the code might fail in real life.

I suggest to add an option to `clock.tick(ms[, shouldRunSimultaneousHandlersInReversOrder])` as an API for test writers who want to test against this problem. The option basically will affect [these lines](https://github.com/sinonjs/lolex/blob/a93c8a9af05fb064ae5c2ad1bfc72874973167ee/src/lolex.js#L193-L206) (maybe only last two `if`s), I think.

----
More context: https://github.com/rpominov/kefir/issues/134 https://github.com/rpominov/kefir/pull/135
cc @AgentME

**Comment by fatso83** [comment]
This feature request is very unlikely to be prioritized by us, so I am closing this, but you could submit a PR. The API might have to be discussed a bit though, but that's just details.
