### ISSUE TITLE
TypeError: Cannot set property performance of #<Object> which has only a getter

### ISSUE THREAD

**Issue by cdow** [sinonjs/lolex#243]
* Lolex version : 4.0.1
* Environment   : node@10.15.1
* Other libraries you are using: 
  - jsdom@15.1.0

This is an issue that was raised before as #197. That issue links to code changes that would probably fix this issue.  However, those changes never appeared to have made it to `master`.

**What did you expect to happen?**
Lolex to initialize without error

**What actually happens**
I get the stack trace:
```
/Users/cdow2/workspace/lolex-test/node_modules/lolex/src/lolex-src.js:451
            target[method] = clock[method];
                           ^

TypeError: Cannot set property performance of #<Object> which has only a getter
    at hijackMethod (/Users/cdow2/workspace/lolex-test/node_modules/lolex/src/lolex-src.js:451:28)
    at Object.install (/Users/cdow2/workspace/lolex-test/node_modules/lolex/src/lolex-src.js:923:17)
    at Object.<anonymous> (/Users/cdow2/workspace/lolex-test/index.js:35:21)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
```

**How to reproduce**
I'm trying to use the jsdom setup for enzyme described [here](https://github.com/airbnb/enzyme/blob/master/docs/guides/jsdom.md).  This can be reproduced by creating an node project with the following files:

<details>
    <summary>package.json</summary>

```json
{
  "name": "lolex-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "node index.js"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "jsdom": "^15.1.0",
    "lolex": "^4.0.1"
  }
}
```
</details>

<details>
    <summary>index.js</summary>

```js

//
// Setup described in: https://github.com/airbnb/enzyme/blob/master/docs/guides/jsdom.md
//
const { JSDOM } = require('jsdom');

const jsdom = new JSDOM('<!doctype html><html><body></body></html>');
const { window } = jsdom;

function copyProps(src, target) {
  Object.defineProperties(target, {
    ...Object.getOwnPropertyDescriptors(src),
    ...Object.getOwnPropertyDescriptors(target),
  });
}

global.window = window;
global.document = window.document;
global.navigator = {
  userAgent: 'node.js',
};
global.requestAnimationFrame = function (callback) {
  return setTimeout(callback, 0);
};
global.cancelAnimationFrame = function (id) {
  clearTimeout(id);
};
copyProps(window, global);

//
// Main code
//
const lolex = require('lolex');
const clock = lolex.install();
clock.uninstall();
```
</details>

Then run the following commands:
```
npm install
npm start
```

**Comment by cdow** [comment]
My workaround for now is to temporarily delete the global `performance` property:
```
const lolex = require('lolex');

const globalPerformance = Object.getOwnPropertyDescriptor(global, 'performance');
delete global.performance;
const clock = lolex.install();

// do stuff that needs the clock replaced

clock.uninstall();
Object.defineProperty(global, 'performance', globalPerformance);
```

This appears to allow lolex to replace `new Date()` appropriately.  However, `Date.now()` still gives the real time.

**Comment by fatso83** [comment]
Good bug report. I don't have time to look into this right, but someone else might. If you have a chance to see if there is some context in the history of #197 that seems to have been lost in the proposed fix, you can try to supply a PR if you get it working somehow (usually the fastest way).

**Comment by eljenso** [comment]
Is there any update on this? @fatso83

**Comment by fatso83** [comment]
I am not (planning on) working on this. Too swamped. Feel free to submit a PR, @eljenso, and I'll take a look at it when time permits :-)

**Comment by cdow** [comment]
I was planning on putting together a PR in the next week.

**Comment by fatso83** [comment]
@cdow Unfortunately, the fix [broke most of the existing browsers](https://travis-ci.org/sinonjs/lolex/jobs/549635521), so I had to revert the fix. I think we need a little bit more testing before the proposed fix will work (testing that the property descriptors are actually writable, for instance).

**Comment by cdow** [comment]
D'oh.  I'll see if I can create a new PR that doesn't break all of the browsers.

**Comment by alexgurr** [comment]
I am still having this issue within my jest/node environment when running `clock.uninstall()`

`Cannot set property performance of [object Object] which has only a getter`

At code:

```
  } else if (originalPerfDescriptor.configurable) {
    target[method] = clock["_" + method];
  }
```
