### ISSUE TITLE
`Date()` should return a string, not an object, in Lolex v4.1.0

### ISSUE THREAD

**Issue by moll** [sinonjs/lolex#246]
Hey,

I believe Lolex deviates from the JavaScript standard behavior with regards to what `Date()` returns. I noticed this through a bug in my code that passed all tests, yet failed in production: I was creating a new date without `new` — `Date(2015, 5, 18)`. In tests, that was equivalent to `new Date(..)`, but without mocking, it returns the current time as a string — an entirely different result. It seems to be an issue already since the times of Sinon v1.17.7 and possibly earlier. Here's an example from RunKit https://runkit.com/embed/delfomea61tm with Lolex v4.1.

```js
require("lolex").install()
Date(2015, 5, 18) // => Thu Jun 18 2015 00:00:00 GMT+0000 (Coordinated Universal Time)
```

**Comment by fatso83** [comment]
Verified! The standard is strange :)

**Comment by moll** [comment]
I think the stale bot is too eager here.
