### ISSUE TITLE
Request: clock.runnedTimers()

### ISSUE THREAD

**Issue by ViktorPegy** [sinonjs/lolex#249]
Feature request: add a function, thats allow to get count of runned timers.  
Eg.:
```js
clock.setTimeout(() => {
  clock.setTimeout(() => {}, 10);
}, 10);
clock.countTimers(); // 1
clock.runAll();
clock.countTimers(); // 0
clock.runnedTimers(); // 2 <----- useful function
```

**Comment by fatso83** [comment]
What's the use case? I don't oppose this, but I think this will have a much better chance if you supply a PR with the changes. The code base is very simple to work with :)
