### ISSUE TITLE
hrtime is affected when setSystemTime() is called multiple times

### ISSUE THREAD

**Issue by SanderDeWaal1992** [sinonjs/lolex#286]
hrtime is affected when setSystemTime() is called multiple times which breaks our unit-tests. This is introduced in issue #214.

* Lolex version :5.1.1
* Environment   : 
* Example URL   : 
* Other libraries you are using:

**What did you expect to happen?**
setSystemTime() should not ever affect hrtime.
**What actually happens**
It does affect hrtime the second time it is called
**How to reproduce**
Call setSystemTime() twice

PR #287 solves this issue.

**Comment by SimenB** [comment]
#287
