### ISSUE TITLE
createDate breaks the Date creation specs

### ISSUE THREAD

**Issue by fraisse** [sinonjs/lolex#39]
Hi,
first of fall, thanks for your work. It is a nice library very useful when using dates…

Just, I think the `createDate` function breaks the actual native `Date` creation, essentially when it is used with one parameter. 
For  `new Date(value)` value could be:
   • an Integer value representing the number of milliseconds since 1 January 1970 00:00:00 UTC (Unix Epoch);
   • an String value representing a date. The string should be in a format recognized by the Date.parse() method

In the lolex `createDate`, the `value` represents only the year of the new Date.
Then, the result is not as really expected.

**Comment by fatso83** [comment]
You are correct that the one argument case is a special case, but you have not demonstrated that the implementation actually produces wrong results in code!

Please give an example of how  lolex handles this incorrectly. 

I just glanced over the code, and although the parameter is called `year`, it is simply passed on, so it could well be a date string. So the code is probably misleading, but not wromg :-)

**Comment by fraisse** [comment]
You absolutely right ;-)
If you're interested, I add two tests in the PR #43 in order to show what you explained.

**Comment by fatso83** [comment]
Thanks for the feedback :)
