### ISSUE TITLE
npm test fails

### ISSUE THREAD

**Issue by pabigot** [sinonjs/lolex#49]
`npm test` invokes `npm run lint` which fails, AFAICT due to checked style violations that have been present in the code for a long time.

If I remove that step the tests pass but having `npm test` fail on a clean checkout and install of the development repository leaves an unjustified negative impression of lolex's quality.

    > lolex@1.4.0 test /opt/Node/lolex
    > npm run lint && npm run test-node && npm run test-headless
    
    
    > lolex@1.4.0 lint /opt/Node/lolex
    > jslint src/**/*.js
    
    
    src/lolex-src.js
     #1 Wrap this regexp in parens to avoid confusion.
        if (l > 3 || !/^(\d\d:){0,2}\d\d?$/.test(str)) { // Line 56, Pos 22
     #2 Unexpected 'for'.
        for (prop in source) { // Line 103, Pos 8
     #3 Unexpected 'arguments'.
        switch (arguments.length) { // Line 144, Pos 20
     #4 Unexpected '++'.
        timer.id = uniqueTimerId++; // Line 176, Pos 32
     #5 Unexpected 'for'.
        for (id in timers) { // Line 236, Pos 8
     #6 Unexpected 'for'.
        for (id in timers) { // Line 254, Pos 8
     #7 Unexpected 'eval'.
        eval(timer.func); // Line 278, Pos 16
     #8 Unexpected 'for'.
        for (i = 0, l = clock.methods.length; i < l; i++) { // Line 340, Pos 8
     #9 Expected ';' and instead saw ','.
        for (i = 0, l = clock.methods.length; i < l; i++) { // Line 340, Pos 18
    
    npm ERR! Linux 3.13.0-83-generic
    npm ERR! argv "/usr/local/Node-v4.4.0/bin/node" "/usr/local/bin/npm" "run" "lint"

**Comment by mantoni** [comment]
I just did this:

```
$ git pull
$ rm -rf node_modules
$ npm i
$ npm t

[master]$ npm t

> lolex@1.4.0 test /Users/max/projects/lolex
> npm run lint && npm run test-node && npm run test-headless


> lolex@1.4.0 lint /Users/max/projects/lolex
> jslint src/**/*.js


src/lolex-src.js is OK.

> lolex@1.4.0 test-node /Users/max/projects/lolex
> mocha -R dot



  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․
  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․

  137 passing (598ms)


> lolex@1.4.0 test-headless /Users/max/projects/lolex
> mochify

# phantomjs:


  ......................................................................................................
  ............................

  130 passing (156ms)
```

Looks like decent quality to me ;-)

Can you please make sure you are on latest HEAD and re-install your dependencies freshly?

**Comment by pabigot** [comment]
No good; see below.  Maybe you have a globally installed jslint that doesn't do anything?  The errors I see are certainly valid complaints from jslint.

    llc[35]$ git describe HEAD
    v1.4.0-27-g5b826f3
    llc[36]$ rm -rf node_modules
    llc[37]$ npm install
    npm WARN deprecated graceful-fs@2.0.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
    npm WARN optional dep failed, continuing fsevents@1.0.11
    -
    > spawn-sync@1.0.15 postinstall /opt/Node/lolex/node_modules/mochify/node_modules/phantomic/node_modules/cross-spawn/node_modules/spawn-sync
    > node postinstall
    
    |
    > mochify@2.17.0 postinstall /opt/Node/lolex/node_modules/mochify
    > node scripts/postinstall.js
    
    => Finding PhantomJS
    => PhantomJS not present locally; checking PATH
    => PhantomJS not present in PATH
    => Attempting to install PhantomJS locally
    npm WARN deprecated phantomjs@2.1.3: Package renamed to phantomjs-prebuilt. Please update 'phantomjs' package references to 'phantomjs-prebuilt'
    
    > phantomjs@2.1.3 install /opt/Node/lolex/node_modules/mochify/node_modules/phantomjs
    > node install.js
    
    PhantomJS not found on PATH
    Download already available at /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
    Verified checksum of previously downloaded file
    Extracting tar contents (via spawned process)
    Removing /opt/Node/lolex/node_modules/mochify/node_modules/phantomjs/lib/phantom
    Copying extracted folder /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2-extract-1459506576781/phantomjs-2.1.1-linux-x86_64 -> /opt/Node/lolex/node_modules/mochify/node_modules/phantomjs/lib/phantom
    Writing location.js file
    Done. Phantomjs binary available at /opt/Node/lolex/node_modules/mochify/node_modules/phantomjs/lib/phantom/bin/phantomjs
    phantomjs@2.1.3 node_modules/phantomjs
    ├── progress@1.1.8
    ├── kew@0.7.0
    ├── adm-zip@0.4.7
    ├── md5@2.0.0 (crypt@0.0.1, charenc@0.0.1, is-buffer@1.0.2)
    ├── request-progress@2.0.1 (throttleit@1.0.0)
    ├── fs-extra@0.26.7 (path-is-absolute@1.0.0, klaw@1.1.3, jsonfile@2.2.3, graceful-fs@4.1.3, rimraf@2.5.2)
    └── request@2.67.0 (aws-sign2@0.6.0, forever-agent@0.6.1, tunnel-agent@0.4.2, oauth-sign@0.8.1, is-typedarray@1.0.0, caseless@0.11.0, stringstream@0.0.5, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, tough-cookie@2.2.2, node-uuid@1.4.7, qs@5.2.0, combined-stream@1.0.5, form-data@1.0.0-rc4, mime-types@2.1.10, hawk@3.1.3, bl@1.0.3, http-signature@1.1.1, har-validator@2.0.6)
    => Successfully installed PhantomJS.  To link it globally, execute:
    	cd node_modules/phantomjs && npm link
    => Mochify install complete!
    sinon@1.17.3 node_modules/sinon
    ├── formatio@1.1.1
    ├── samsam@1.1.2
    ├── lolex@1.3.2
    └── util@0.10.3 (inherits@2.0.1)
    
    mocha@2.4.5 node_modules/mocha
    ├── escape-string-regexp@1.0.2
    ├── commander@2.3.0
    ├── diff@1.4.0
    ├── growl@1.8.1
    ├── supports-color@1.2.0
    ├── debug@2.2.0 (ms@0.7.1)
    ├── mkdirp@0.5.1 (minimist@0.0.8)
    ├── jade@0.26.3 (commander@0.6.1, mkdirp@0.3.0)
    └── glob@3.2.3 (inherits@2.0.1, graceful-fs@2.0.3, minimatch@0.2.14)
    
    jslint@0.9.6 node_modules/jslint
    ├── exit@0.1.2
    ├── nopt@3.0.6 (abbrev@1.0.7)
    ├── readable-stream@1.0.33 (string_decoder@0.10.31, isarray@0.0.1, inherits@2.0.1, core-util-is@1.0.2)
    └── glob@4.5.3 (inherits@2.0.1, once@1.3.3, inflight@1.0.4, minimatch@2.0.10)
    
    referee@1.2.0 node_modules/referee
    ├── bane@1.1.2
    ├── samsam@1.2.1
    └── lodash@3.10.1
    
    browserify@12.0.2 node_modules/browserify
    ├── https-browserify@0.0.1
    ├── tty-browserify@0.0.0
    ├── path-browserify@0.0.0
    ├── punycode@1.4.1
    ├── duplexer2@0.1.4
    ├── constants-browserify@1.0.0
    ├── string_decoder@0.10.31
    ├── browser-resolve@1.11.1
    ├── isarray@0.0.1
    ├── through2@2.0.1
    ├── os-browserify@0.1.2
    ├── inherits@2.0.1
    ├── process@0.11.2
    ├── htmlescape@1.1.1
    ├── stream-browserify@2.0.1
    ├── assert@1.3.0
    ├── defined@1.0.0
    ├── domain-browser@1.1.7
    ├── xtend@4.0.1
    ├── read-only-stream@2.0.0
    ├── querystring-es3@0.2.1
    ├── timers-browserify@1.4.2
    ├── deps-sort@2.0.0
    ├── util@0.10.3
    ├── concat-stream@1.5.1 (typedarray@0.0.6)
    ├── events@1.1.0
    ├── parents@1.0.1 (path-platform@0.11.15)
    ├── shell-quote@1.5.0 (array-filter@0.0.1, array-map@0.0.0, array-reduce@0.0.0, jsonify@0.0.0)
    ├── console-browserify@1.1.0 (date-now@0.1.4)
    ├── readable-stream@2.0.6 (process-nextick-args@1.0.6, util-deprecate@1.0.2, core-util-is@1.0.2, isarray@1.0.0)
    ├── vm-browserify@0.0.4 (indexof@0.0.1)
    ├── subarg@1.0.0 (minimist@1.2.0)
    ├── has@1.0.1 (function-bind@1.1.0)
    ├── url@0.11.0 (punycode@1.3.2, querystring@0.2.0)
    ├── labeled-stream-splicer@2.0.0 (stream-splicer@2.0.0)
    ├── shasum@1.0.2 (sha.js@2.4.5, json-stable-stringify@0.0.1)
    ├── stream-http@2.2.1 (builtin-status-codes@2.0.0, to-arraybuffer@1.0.1)
    ├── glob@5.0.15 (path-is-absolute@1.0.0, once@1.3.3, inflight@1.0.4, minimatch@3.0.0)
    ├── buffer@3.6.0 (ieee754@1.1.6, isarray@1.0.0, base64-js@0.0.8)
    ├── JSONStream@1.1.1 (through@2.3.8, jsonparse@1.2.0)
    ├── syntax-error@1.1.6 (acorn@2.7.0)
    ├── resolve@1.1.7
    ├── browserify-zlib@0.1.4 (pako@0.2.8)
    ├── browser-pack@6.0.1 (umd@3.0.1, combine-source-map@0.7.1)
    ├── insert-module-globals@7.0.1 (is-buffer@1.1.3, combine-source-map@0.7.1, lexical-scope@1.2.0)
    ├── crypto-browserify@3.11.0 (create-hmac@1.1.4, randombytes@2.0.3, pbkdf2@3.0.4, create-hash@1.1.2, diffie-hellman@5.0.2, create-ecdh@4.0.0, browserify-cipher@1.0.0, public-encrypt@4.0.0, browserify-sign@4.0.0)
    └── module-deps@4.0.5 (stream-combiner2@1.1.1, detective@4.3.1)
    
    mochify@2.17.0 node_modules/mochify
    ├── brout@1.1.0
    ├── subarg@1.0.0 (minimist@1.2.0)
    ├── source-mapper@2.0.0 (convert-source-map@1.2.0, source-map@0.5.3)
    ├── which@1.2.4 (isexe@1.1.2, is-absolute@0.1.7)
    ├── consolify@2.1.0 (browser-reload@1.1.0, ansi_up@1.3.0)
    ├── mocaccino@1.8.2 (listen@1.0.0, supports-color@3.1.2)
    ├── through2@2.0.1 (xtend@4.0.1, readable-stream@2.0.6)
    ├── resolve@1.1.7
    ├── glob@6.0.4 (path-is-absolute@1.0.0, inherits@2.0.1, inflight@1.0.4, once@1.3.3, minimatch@3.0.0)
    ├── coverify@1.4.1 (slash@1.0.0, split2@0.2.1, convert-source-map@1.2.0, minimist@1.2.0, source-map@0.4.4, through2@0.6.5, stream-combiner2@1.1.1, falafel@1.2.0)
    ├── min-wd@2.9.0 (listen@1.0.0, saucelabs@1.2.0)
    ├── phantomic@1.4.0 (es5-shim@4.5.7, cross-spawn@2.1.5)
    ├── watchify@3.7.0 (defined@1.0.0, xtend@4.0.1, outpipe@1.1.1, chokidar@1.4.3, anymatch@1.3.0)
    └── browserify@13.0.0 (https-browserify@0.0.1, tty-browserify@0.0.0, path-browserify@0.0.0, duplexer2@0.1.4, punycode@1.4.1, string_decoder@0.10.31, browser-resolve@1.11.1, constants-browserify@1.0.0, isarray@0.0.1, os-browserify@0.1.2, inherits@2.0.1, htmlescape@1.1.1, process@0.11.2, stream-browserify@2.0.1, assert@1.3.0, defined@1.0.0, domain-browser@1.1.7, xtend@4.0.1, read-only-stream@2.0.0, querystring-es3@0.2.1, timers-browserify@1.4.2, deps-sort@2.0.0, util@0.10.3, concat-stream@1.5.1, events@1.1.0, parents@1.0.1, shell-quote@1.5.0, console-browserify@1.1.0, readable-stream@2.0.6, vm-browserify@0.0.4, has@1.0.1, url@0.11.0, labeled-stream-splicer@2.0.0, shasum@1.0.2, stream-http@2.2.1, glob@5.0.15, buffer@4.5.1, JSONStream@1.1.1, syntax-error@1.1.6, browserify-zlib@0.1.4, browser-pack@6.0.1, insert-module-globals@7.0.1, crypto-browserify@3.11.0, module-deps@4.0.5)
    llc[38]$ 
    llc[38]$ npm test
    
    > lolex@1.4.0 test /opt/Node/lolex
    > npm run lint && npm run test-node && npm run test-headless
    
    
    > lolex@1.4.0 lint /opt/Node/lolex
    > jslint src/**/*.js
    
    
    src/lolex-src.js
     #1 Wrap this regexp in parens to avoid confusion.
        if (l > 3 || !/^(\d\d:){0,2}\d\d?$/.test(str)) { // Line 56, Pos 22
     #2 Unexpected 'for'.
        for (prop in source) { // Line 103, Pos 8
     #3 Unexpected 'arguments'.
        switch (arguments.length) { // Line 144, Pos 20
     #4 Unexpected '++'.
        timer.id = uniqueTimerId++; // Line 176, Pos 32
     #5 Unexpected 'for'.
        for (id in timers) { // Line 236, Pos 8
     #6 Unexpected 'for'.
        for (id in timers) { // Line 254, Pos 8
     #7 Unexpected 'eval'.
        eval(timer.func); // Line 278, Pos 16
     #8 Unexpected 'for'.
        for (i = 0, l = clock.methods.length; i < l; i++) { // Line 340, Pos 8
     #9 Expected ';' and instead saw ','.
        for (i = 0, l = clock.methods.length; i < l; i++) { // Line 340, Pos 18
    
    npm ERR! Linux 3.13.0-83-generic
    npm ERR! argv "/usr/local/Node-v4.4.0/bin/node" "/usr/local/bin/npm" "run" "lint"
    npm ERR! node v4.4.0
    npm ERR! npm  v2.14.20
    npm ERR! code ELIFECYCLE
    npm ERR! lolex@1.4.0 lint: `jslint src/**/*.js`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the lolex@1.4.0 lint script 'jslint src/**/*.js'.
    npm ERR! This is most likely a problem with the lolex package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     jslint src/**/*.js
    npm ERR! You can get information on how to open an issue for this project with:
    npm ERR!     npm bugs lolex
    npm ERR! Or if that isn't available, you can get their info via:
    npm ERR! 
    npm ERR!     npm owner ls lolex
    npm ERR! There is likely additional logging output above.
    
    npm ERR! Please include the following file with any support request:
    npm ERR!     /opt/Node/lolex/npm-debug.log
    npm ERR! Test failed.  See above for more details.
    llc[39]$

**Comment by pabigot** [comment]
Apologies; this was my error.  I have a global `.jslint.conf`:

    {
        "edition": "latest"
    }

which is a bit more strict than the default.  Removing that everything passes.

**Comment by mantoni** [comment]
Ha, I managed to reproduce, but that’s a really strange issue:

If I run `node_modules/.bin/jslint src/**/*.js` to make sure I’m using the same version as the npm lint script, jslint doesn’t complain about anything. However, if I run `node_modules/.bin/jslint src/**/*.js --edition=latest`, I get the exact same output as you. I have no idea why jslint uses different editions for the two of us.

Anyway, we can fix this, but Sinon moved to eslint recently, and so should this module.

**Comment by mantoni** [comment]
Both typing at the same time haha. Thanks for demystifying!

**Comment by pabigot** [comment]
I don't use jslint anymore either, which is probably why I forgot about that file.  (jscs + jshint for my stuff.)
