### ISSUE TITLE
How to use `runAll`

### ISSUE THREAD

**Issue by hotaru355** [sinonjs/lolex#54]
I am trying to set the system time and then run all asynchronous code in a test like this:

```js
var clock = lolex.install();
clock.setSystemTime(moment.utc('2016-04-01').valueOf());
clock.runAll();
```

But it seems that the method is not defined: 
```js
TypeError: clock.runAll is not a function
```

Could you please point me in the right direction. Thank you!

lolex: 1.4.0
nodeJs: 5.2

**Comment by mantoni** [comment]
This feature was added just last week and is not yet released.

**Comment by hotaru355** [comment]
Is there any way I could get the same results with the current release? Something like running `clock.next()` or `clock.tick()` in a loop for example?

**Comment by fatso83** [comment]
Btw, 1.5.0 is out.
