### ISSUE TITLE
Links on sinonjs.org for lolex files return 404s

### ISSUE THREAD

**Issue by ryanwalls** [sinonjs/lolex#55]
Try http://sinonjs.org/releases/sinon-timers-1.17.3.js

**Comment by fatso83** [comment]
We are aware of this and it will be addressed in the new Sinon homepage, but ETA of that is uncertain.

**Comment by fatso83** [comment]
The built releases can be downloaded from this repo and the Sinon homepage no longer hosts the timer packages separately.
