### ISSUE TITLE
Cannot set property 'hrtime' of undefined

### ISSUE THREAD

**Issue by gautaz** [sinonjs/lolex#59]
Hello,

After migrating from lolex 1.4.0 to 1.5.0, my tests fails with this exception:
```javascript
     TypeError: Cannot set property 'hrtime' of undefined
      at uninstall (node_modules/lolex/src/lolex-src.js:360:39)
      at Object.clock.uninstall (node_modules/lolex/src/lolex-src.js:629:13)
      at bus.close.then.then (test/scheduling/testScheduler.js:64:57)
```

I'm using nodejs 6.2.0.

My tests use lolex this way:

Setup:
```javascript
clock = lolex.install(context)
```

Tear down:
```javascript
clock.uninstall()
```

[lolex-src.js 1.5.0](https://github.com/sinonjs/lolex/blob/v1.5.0/src/lolex-src.js#L360) seems to assume that the context object has a key named `process`.

Any idea regarding this ? Does this mean that compatibility was broken somehow ?

**Comment by fatso83** [comment]
@rogierschouten Could this be related to #40 ?

**Comment by gautaz** [comment]
You are right, the breaking code was added by this merge.

Doesn't this means that 1.5.0 breaks backward compatibility and should be tagged as 2.0.0 (a migration note can also probably help)?
Or perhaps the code should be modified to not rely on target.process?

**Comment by fatso83** [comment]
@gautaz This breaking change was unintentional. Needs a bugfix.

**Comment by rogierschouten** [comment]
looking into it now

**Comment by rogierschouten** [comment]
Issued PR #62 for this. I could not reproduce the issue in any way also not in a browser. However, the code was clearly not airtight so I think this would fix it.

**Comment by fatso83** [comment]
@gautaz Could you please provide a test case that is runnable in Node? I could then squash that together with #62 if that indeed fixes it.

**Comment by gautaz** [comment]
Here it is: #65

**Comment by fatso83** [comment]
@rogierschouten Mind seeing if @gautaz test breaks for you? If so, then you have your reproducible test case. You could then merge that into #62 (just remove the built source).

**Comment by rogierschouten** [comment]
@fatso83 done

**Comment by fatso83** [comment]
Fixed. Will release a new version asap.
