### ISSUE TITLE
useFakeTimers breaks test when used with native callbacks

### ISSUE THREAD

**Issue by ilgooz** [sinonjs/lolex#66]
Test timeouts when I do have callbacks for native events in my code. removing fake timer from code makes it work again.
```js
var test = require('tape');
var sinon = require('sinon');

test('1', (t) => {
  t.plan(1);

  var clock = sinon.useFakeTimers();

  var p = new webkitRTCPeerConnection({iceServers: []})
  p.createOffer(function(){ t.ok(true); }, function(){});
});
```
Chrome 50.0.2661 (Linux 0.0.0)

thank you

**Comment by ilgooz** [comment]
as I check this issue occur with tape. mocha works as expected. feel free to close the issue if you think there is nothing to do with lolex to solve this. I'll share my solution here if I find any.

**Comment by mantoni** [comment]
I know that Mocha keeps a reference to setTimeout for it's own use, specifically to allow stubbing it in tests. Maybe tape doesn't do that and relies on setTimeout internally?

**Comment by ilgooz** [comment]
it is true. it depends(calls process.nextTick) on setTimeout only when doing async execution(xhr calls, browser native async operations, events that executed in async but not relevant with time). calling _clock.tick(1)_ after assertion solves this problem(this where process.nextTick is called) but this is a quite ugly solution. the problem with test is, assertions works fine but tab output is never ended and this makes karma test to timeout.

following lines are relevant with this 
* https://github.com/substack/tape/commit/978431c8a6db8cf3925a8b1b95a771aa872b9283#diff-dd2e881af3311f834199c7b515cff0c7R92
* used by tape https://github.com/dominictarr/through/commit/903501acf73d03f584dd572b885c78c1bc9cca8b#diff-168726dbe96b3ce427e7fedce31bb0bcR49

**Comment by ilgooz** [comment]
I'll use lolex directly with _createClock()_ and make my class accept a clock interface to not mess with global settings by using _useFakeTimers()_. this looks like the cleanest way to do it.
@mantoni about globals, my 2 cents on checking setTimeout's duration and do not stub it if it's equal to zero since zero value is always meant to be used to do job of _nexTick_. thanks!

**Comment by fatso83** [comment]
Closing this as this is a tape issue. Follow substack/tape#292 for updates or file a PR there to see it fixed.

**Comment by fatso83** [comment]
@ilgooz : I filed an issue with `tape` and that is already fixed. Also filed on with `through`, so you might want to follow that one too: dominictarr/through#43. Or perhaps supply a fix if you really want to see it fixed ;-)

**Comment by ilgooz** [comment]
@fatso83 yes thanks. :')
