### ISSUE TITLE
Maintain sorted list of timers

### ISSUE THREAD

**Issue by duncanbeevers** [sinonjs/lolex#7]
Currently the list of timers is stored as a flat, unsorted object space.

We may improve performance by maintaining an array of timers-to-be-executed, explicitly sorted according to their eventual execution order.

New timers could be inserted using a binary search insertion, turning the current O(1) operation to an O(logn) operation, but turning the execution-time cost from the current O(n)-ish to O(1).

**Comment by mroderick** [comment]
This hasn't seen any activity in more than six months, I am closing it.

Feel free to re-open for further discussion or pull requests
