### ISSUE TITLE
jQuery.now does not respect lolex's fake timer

### ISSUE THREAD

**Issue by gmcnaughton** [sinonjs/lolex#76]
This isn't a lolex bug per se, but a gotcha that I wanted to report here just in case anyone else runs into it!

If you use jQuery 2/3, [$.now()](http://api.jquery.com/jquery.now/) will not respect lolex's fake timer.  jQuery 1.x used to respect it.  This is because jQuery 2/3 captures a reference to `Date.now` at load time, before lolex gets a chance to stub it out.  You see results like this:

    > Date.now()
    < 36000000

    > (new Date).getTime()
    < 36000000

    > $.now()
    < 1468845725858

The jQuery docs claim "The $.now() method is a shorthand for the number returned by the expression (new Date).getTime().", but that's not quite right - it's defined as `now: Date.now`, which captures a reference to the original unstubbed method.

**Comment by gmcnaughton** [comment]
Our workaround was a shim that forcibly reverts jQuery's logic:

````javascript
// Revert jQuery.now back to its 1.x behavior, so that it respects lolex's fake timers
(function($) {
  $.now = function() { return +( new Date() ); };
})(jQuery);
````

**Comment by fatso83** [comment]
OK, thanks for documenting it. Closing.
