### ISSUE TITLE
Install clock to multiple targets

### ISSUE THREAD

**Issue by taylor1791** [sinonjs/lolex#83]
In node, there are the global `setTimeout` and friends. In addition, there are `require('timers').setTimeout` and friends. If I need to mock both, I can do the following.

```
global.clock1 = lolex.install();
global.clock2 = lolex.install(require('timers'), 0, ['setTimeout']);
```

However, if a library uses both, I have to know when to call each of them (which could change between releases). It would be awesome if I could tell `lolex.install` to use a specified clock. In this case, I would make both mocks have the same clock.

**Comment by benjamingr** [comment]
This is no longer an issue in modern Node:

0.12:
```
> require("timers").setTimeout === setTimeout
false
```

v4
```
> require("timers").setTimeout === setTimeout
true
```

v8
```
> require("timers").setTimeout === setTimeout
true
```

**Comment by fatso83** [comment]
Thanks for the investigation, @benjamingr ! Closing.
