### ISSUE TITLE
Option of throwing when timers remain on uninstall

### ISSUE THREAD

**Issue by Moeriki** [sinonjs/lolex#84]
A good test doesn't mock more than it needs to. Thus I would expect that when I call `clock.uninstall()` there would be no uncalled timers left.

Yet sometimes I suck at writing tests and would have a false positive / negative, or even worse, a silent error dangling in a `setImmediate` that never got called.

It would be tremendously helpful if we could log a warning (or throw) when there are uncalled timer functions. Either by default, or as an option.

**Comment by benjamingr** [comment]
I can start working on this if you'd like, basically the logic is:

If uninstall is called and `clock.timers.length > 0` then emit a `console.warn`.

What behavior would you prefer @fatso83 ?

 - Throw on timers remaining?
 - Warn on timers remaining? 
 - Ignore on timers remaining? (Current behavior).

I'll also run the change on the Peer5 tests that use lolex (about 300) and see how it affects them.

**Comment by fatso83** [comment]
Could be a three-option setting ("ignore", "error", "warn"), where we could set a new default. A lot of people don't like `console` statements filling up their tests, but then they at least have the option of turning it off.

I am not totally sure what would be a good default here. Maybe @mroderick could chime in with an opinion.

**Comment by benjamingr** [comment]
@fatso83 we could `process.warn` on Node and throw in browsers - although lolex is used in tests so I doubt it would cause availability issues.

I'm :+1: on throwing everywhere in terms of design - but it would be a breaking change. I'm also fine with ignoring by default if NODE_ENV is production and warn otherwise.

**Comment by fatso83** [comment]
Also agree with throwing as a general rule of thumb. But as we shipped 2.0.0 a few days back, it's a bit early for making a new breaking change - warranting a new major version. We could do this as a stepwise refinement, kind of the way we deprecate things in Sinon:
1. Current major version: print warning about non-optimal current design
2. Next major version: Throw error

**Comment by mroderick** [comment]
> I'm 👍 on throwing everywhere in terms of design - but it would be a big breaking change. I'm also fine with ignoring by default if NODE_ENV is production and warn otherwise.

I am with you for throwing. I think @fatso83's suggestion is reasonable!

**Comment by benjamingr** [comment]
So, I completely changed my mind on this after writing the PR, it turns out writing `setInterval` and but not calling `clearInterval` is a pretty common scenario. Another common scenario is doing a `setTimeout` and checking it was _not_ called after a duration - a `clearTimeout` is not used.

To illustrate this - lolex's own test suite emitted 20 warnings for tests like:

```
it("creates updated Date while ticking", function () {
            var spy = sinon.spy();

            this.clock.setInterval(function () {
                spy(new Date().getTime());
            }, 10);

            this.clock.tick(100);
            ...
```

Both lolex's own test suite and our own tests at [Peer5](https://github.com/Peer5/) emitted multiple warnings.

I am now convinced the right thing is to not do anything if there are remaining timers and the clock is uninstalled. We _might_ want to consider having `uninstall` returning a list of remaining timers.

-------------

If anyone wants to play with it themselves:

```diff
diff --git a/src/lolex-src.js b/src/lolex-src.js
index 0918420..e76f063 100644
@@ -348,6 +348,24 @@ function clearTimer(clock, timerId, ttype) {
     }
 }
 
+function warnOnPendingTimers(clock) {
+    if (firstTimer(clock)) {
+        var modernNode = global.process && typeof global.process.emitWarning === "function";
+        var hasConsole = global.console && typeof global.console.warn === "function";
+        var warningMessage = "lolex was uninstalled but there are still active fake timers";
+
+        if (modernNode) {
+            process.emitWarning(warningMessage, {
+                type: "DeprecationWarning",
+                detail: clock.timers
+            });
+        } else if (hasConsole) {
+            /* eslint no-console : "off" */
+            console.warn(warningMessage, clock.timers);
+        }
+    }
+}
+
 function uninstall(clock, target, config) {
     var method,
         i,
@@ -372,6 +390,9 @@ function uninstall(clock, target, config) {
         }
     }
 
+    // Warn if there are unexecuted lolex timers when uninstalling
+    warnOnPendingTimers(clock);
+
     // Prevent multiple executions which will completely remove these props
     clock.methods = [];
 }
```

**Comment by fatso83** [comment]
Good points you raise there, Benjamin. I guess we could still supply throwing an exception as a feature that can be toggled on (off by default). I also like that `uninstall` could return the timers. Maybe it would return a structured object of some kind like `{ setTimeout: [], setInterval: [], ...}`. Not sure how easy this would be to implement, though.

**Comment by mroderick** [comment]
> We might want to consider having uninstall returning a list of remaining timers

That seems reasonable

**Comment by fatso83** [comment]
With @benjamingr's code I think this is a low-hanging fruit to implement. Added a better title for clarity.

**Comment by benjamingr** [comment]
I can pick this up

**Comment by benjamingr** [comment]
Can't self assign, feel free to assign me and I'll take a stab tomorrow.

**Comment by benjamingr** [comment]
@Moeriki I know it's been a year - but would love your feedback on the solution proposed in https://github.com/sinonjs/lolex/pull/141 and discussed here

**Comment by Moeriki** [comment]
I rarely use Lolex anymore so it's hard to consider my previous use-case. That said returning a list of timers on uninstall seems like a safe way to resolve this issue.

Let users assert the remaining timers themselves. Flexible 💪 and easy to reason  about. I like it. 👍
