### ISSUE TITLE
Time travel without freezing

### ISSUE THREAD

**Issue by jvdp** [sinonjs/lolex#85]
I'd like to use this library for acceptance tests (ie. running the web app + JS frontend in a browser / phantomjs) that involve time-dependent data, so the clock needs to be set back to a certain date. My app also uses lodash' `debounce` function, however, which relies on the passage of time. Because I don't really have a good place to put a `tick` statement the clock shouldn't be 'frozen' at a particular moment but it should advance as normal from the system date specified.

This would like the `travel` method of [Timecop.js](https://github.com/jamesarosen/Timecop.js) (which is [deprecated](https://github.com/jamesarosen/Timecop.js/issues/28#issuecomment-227208629) in favor of sinon / lolex.)

**Comment by fatso83** [comment]
I don't see how this could be implemented without async behaviour, which means you just might as well just put `tick` calls in some endless `setInterval` or `process.nextTick` loop yourself.

**Comment by jvdp** [comment]
We can take a timestamp of when time travel starts and then compute the difference to determine the adjust "current" time. Timecop.js does this: https://github.com/jamesarosen/Timecop.js/blob/master/lib/TimeStackItem.js

**Comment by fatso83** [comment]
True, just computing the `now`value based on the diff is easily done. Such a feature should be quite easily implemented. Must have been to late to think clearly 😄  Care to take a stab at it?

**Comment by jvdp** [comment]
Will see what I can do.

**Comment by mroderick** [comment]
Has this issue stalled?

**Comment by fatso83** [comment]
Will be closed by #102

**Comment by fatso83** [comment]
closed by #102
