### ISSUE TITLE
Pre-built browser version in README doesn't exist

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [sinonjs/lolex#90]
> If you want to use Lolex in a browser you can use the [pre-built version](https://github.com/sinonjs/lolex/edit/master/lolex.js) available in the repo and the npm package. Using npm you only need to reference ./node_modules/lolex/lolex.js in your <script> tags.

The linked file doesn't actually exist.

**Comment by fatso83** [comment]
Oh, it does exist, but only for us maintainers ;-) Sorry about that. Changed `edit` to `blob` in the PR. Thanks for the heads up!

**Comment by JoshuaKGoldberg** [comment]
:) thanks!
