### ISSUE TITLE
Chai extension for lolex, like sinon-chai

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [sinonjs/lolex#95]
https://github.com/domenic/sinon-chai exists and is great. I haven't been able to find an equivalent for lolex. 

* Is there one?
* If I were to write such a thing, would you want ownership of it?

**Comment by cjohansen** [comment]
I don't know of one. If you want to host the module under the sinonjs organization, we sure could.

**Comment by mroderick** [comment]
Is there any traction on this issue?

**Comment by fatso83** [comment]
Closing this as the author has been informed of everything that was requested.
