### ISSUE TITLE
Issue with upgrade from 1.5.1 -> 1.5.2

### ISSUE THREAD

**Issue by krnjn** [sinonjs/lolex#97]
I'm having an issue with a test that works fine on versions 1.5.1 and below that does not seem to work on 1.5.2 (using Jest + Enzyme). Following the README, this should work just fine, but seems to be having issues. Here's a sample of the code for reference:

```
import React from 'react';
import {shallow, mount} from 'enzyme';
import lolex from 'lolex';

import ResponsesSearch from 'js/responses/components/search/index';

  it('calls #applySearchTerm on submit', () => {
    const clock = lolex.install();
    const searchTermFn = jest.fn();
    const wrapper = mount(
      <ResponsesSearch applySearchTerm={searchTermFn} />
    );
    const input = wrapper.find('input');

    input.node.value = 'blah';
    input.simulate('change'); // we have an onChange callback on this input after 500ms

    clock.tick(500);

    expect(searchTermFn).toHaveBeenCalledWith('blah');

    clock.uninstall();
  });
```

I can provide more code if needed, but I'm wondering if I'm doing something wrong here with the implementation of lolex with:

```
const clock = lolex.install();
clock.tick(500);
clock.uninstall();
```

Any help would be appreciated!

**Comment by fatso83** [comment]
As can be seen from the [changelog](https://github.com/sinonjs/lolex/releases) this might be related to #87  which was supposed to fix compatibility with React Native. 

It might be that this is not an actual error/regression in Lolex, but rather exposes some fundamental design flaw in the code you are testing. But if fully might be a problem with lolex too ... See the changes in #87 and see if you can spot something that might be relevant.

**Comment by krnjn** [comment]
@fatso83 thanks for the reply. I'm not sure how the changes in that commit would be causing the issue. For reference, here's the test failure / stack trace provided:

```
 FAIL  spec/js/responses/components/search/index_spec.js.jsx
  ● responses/components/search/index › calls #applySearchTerm on submit

    expect(jest.fn()).toHaveBeenCalledWith(expected)
    
    Expected mock function to have been called with:
      ["blah"]
    But it was not called.
      
      at Object.<anonymous> (spec/js/responses/components/search/index_spec.js.jsx:36:26)
      at handle (node_modules/worker-farm/lib/child/index.js:41:8)
      at process.<anonymous> (node_modules/worker-farm/lib/child/index.js:47:3)
      at emitTwo (events.js:106:13)
      at process.emit (events.js:191:7)
      at process.nextTick (internal/child_process.js:752:12)
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickCallback (internal/process/next_tick.js:98:9)
```

I'll continue looking at it on my end, but let me know if you find anything further / need additional information!

**Comment by cjohansen** [comment]
@krnjn Did you figure out what happened?

**Comment by krnjn** [comment]
@cjohansen nope, just locked down lolex@1.5.1

**Comment by fatso83** [comment]
This has stalled and we have no test case to test against. Closing until someone can show this as an error in lolex
